import type { LessonItem } from '../types/korean';

/**
 * Curated per-Jamo short word banks (1–3 words / length <= 12 characters).
 * Every entry for a given Jamo is strictly composed only of that Jamo and preceding unlocked Jamos.
 */
export const MASTERY_JAMO_VOCABULARY: Record<string, LessonItem[]> = {
  // --- Stage 1: Home Row Index Keys (ㅓ, ㅏ, ㅇ, ㄹ) ---
  ㅓ: [
    { id: 'mv_eo_1', moduleId: 'mastery', target: '어', translation: 'Oh / Well' },
    { id: 'mv_eo_2', moduleId: 'mastery', target: '어어', translation: 'Uh-oh' },
    { id: 'mv_eo_3', moduleId: 'mastery', target: '어어어', translation: 'Oh, oh, oh! (exclamation of surprise)' },
  ],
  ㅏ: [
    { id: 'mv_a_1', moduleId: 'mastery', target: '아', translation: 'Ah' },
    { id: 'mv_a_2', moduleId: 'mastery', target: '아아', translation: 'Ah, ah' },
    { id: 'mv_a_3', moduleId: 'mastery', target: '아아아', translation: 'Ahhh (exclamation)' },
    { id: 'mv_a_4', moduleId: 'mastery', target: '아라', translation: 'Ara (ancient Korean word for sea)' },
  ],
  ㅇ: [
    { id: 'mv_ng_1', moduleId: 'mastery', target: '앙', translation: 'Chomp / Whimper (onomatopoeia)' },
    { id: 'mv_ng_2', moduleId: 'mastery', target: '엉', translation: 'Yes / Huh (casual interjection)' },
    { id: 'mv_ng_3', moduleId: 'mastery', target: '앙앙', translation: 'Wah-wah (crying sound)' },
    { id: 'mv_ng_4', moduleId: 'mastery', target: '엉엉', translation: 'Sobbing sound (boo-hoo)' },
  ],
  ㄹ: [
    { id: 'mv_r_1', moduleId: 'mastery', target: '알', translation: 'Egg / Grain' },
    { id: 'mv_r_2', moduleId: 'mastery', target: '얼', translation: 'Spirit / Soul' },
    { id: 'mv_r_3', moduleId: 'mastery', target: '라', translation: 'Musical note (La)' },
    { id: 'mv_r_4', moduleId: 'mastery', target: '러', translation: 'In order to (grammar ending)' },
    { id: 'mv_r_5', moduleId: 'mastery', target: '알아', translation: 'I know' },
    { id: 'mv_r_6', moduleId: 'mastery', target: '어라', translation: 'Huh? / Oh dear' },
    { id: 'mv_r_7', moduleId: 'mastery', target: '아라', translation: 'Ara (ancient Korean word for sea)' },
    { id: 'mv_r_8', moduleId: 'mastery', target: '얼라', translation: 'Child / Baby (dialect)' },
  ],

  // --- Stage 2: Remaining Home Row & Basic Vowels (ㅗ, ㅣ, ㅁ, ㄴ, ㅎ, ㅜ, ㅡ) ---
  ㅗ: [
    { id: 'mv_o_1', moduleId: 'mastery', target: '오', translation: 'Five / Oh' },
    { id: 'mv_o_2', moduleId: 'mastery', target: '올', translation: 'Strand / Thread strand' },
    { id: 'mv_o_3', moduleId: 'mastery', target: '로', translation: 'Path / Road' },
    { id: 'mv_o_4', moduleId: 'mastery', target: '오라', translation: 'Come (imperative) / Aura' },
    { id: 'mv_o_5', moduleId: 'mastery', target: '올라', translation: 'Go up / Rise' },
    { id: 'mv_o_6', moduleId: 'mastery', target: '오로라', translation: 'Aurora' },
    { id: 'mv_o_7', moduleId: 'mastery', target: '오알', translation: 'OR (operating room / phonetic)' },
  ],
  ㅣ: [
    { id: 'mv_i_1', moduleId: 'mastery', target: '이', translation: 'Tooth / Two / This' },
    { id: 'mv_i_2', moduleId: 'mastery', target: '일', translation: 'One / Day / Work' },
    { id: 'mv_i_3', moduleId: 'mastery', target: '아이', translation: 'Child' },
    { id: 'mv_i_4', moduleId: 'mastery', target: '오이', translation: 'Cucumber' },
    { id: 'mv_i_5', moduleId: 'mastery', target: '이리', translation: 'Wolf / This way' },
    { id: 'mv_i_6', moduleId: 'mastery', target: '일이', translation: 'Work / Task (subject form)' },
    { id: 'mv_i_7', moduleId: 'mastery', target: '릴리', translation: 'Lily' },
  ],
  ㅁ: [
    { id: 'mv_m_1', moduleId: 'mastery', target: '말', translation: 'Horse / Speech / Words' },
    { id: 'mv_m_2', moduleId: 'mastery', target: '몸', translation: 'Body' },
    { id: 'mv_m_3', moduleId: 'mastery', target: '엄마', translation: 'Mom' },
    { id: 'mv_m_4', moduleId: 'mastery', target: '이마', translation: 'Forehead' },
    { id: 'mv_m_5', moduleId: 'mastery', target: '마리', translation: 'Counter for animals' },
    { id: 'mv_m_6', moduleId: 'mastery', target: '모아', translation: 'Gather / Collect' },
    { id: 'mv_m_7', moduleId: 'mastery', target: '모이', translation: 'Bird feed' },
    { id: 'mv_m_8', moduleId: 'mastery', target: '미라', translation: 'Mummy' },
    { id: 'mv_m_9', moduleId: 'mastery', target: '모말', translation: 'Horsehair' },
  ],
  ㄴ: [
    { id: 'mv_n_1', moduleId: 'mastery', target: '나', translation: 'I / Me' },
    { id: 'mv_n_2', moduleId: 'mastery', target: '너', translation: 'You' },
    { id: 'mv_n_3', moduleId: 'mastery', target: '나라', translation: 'Country / Nation' },
    { id: 'mv_n_4', moduleId: 'mastery', target: '나이', translation: 'Age' },
    { id: 'mv_n_5', moduleId: 'mastery', target: '날', translation: 'Day / Blade' },
    { id: 'mv_n_6', moduleId: 'mastery', target: '언니', translation: 'Older sister (used by females)' },
    { id: 'mv_n_7', moduleId: 'mastery', target: '어머니', translation: 'Mother' },
    { id: 'mv_n_8', moduleId: 'mastery', target: '미나리', translation: 'Water dropwort' },
    { id: 'mv_n_9', moduleId: 'mastery', target: '안', translation: 'Inside / Not' },
    { id: 'mv_n_10', moduleId: 'mastery', target: '인', translation: 'Person / Human (Hanja)' },
    { id: 'mv_n_11', moduleId: 'mastery', target: '온', translation: 'All / Whole' },
    { id: 'mv_n_12', moduleId: 'mastery', target: '놀이', translation: 'Play / Game' },
  ],
  ㅎ: [
    { id: 'mv_h_1', moduleId: 'mastery', target: '하나', translation: 'One' },
    { id: 'mv_h_2', moduleId: 'mastery', target: '한', translation: 'One / Korean / Deep sorrow' },
    { id: 'mv_h_3', moduleId: 'mastery', target: '혼', translation: 'Soul / Spirit' },
    { id: 'mv_h_4', moduleId: 'mastery', target: '힘', translation: 'Strength / Power' },
    { id: 'mv_h_5', moduleId: 'mastery', target: '허리', translation: 'Waist / Lower back' },
    { id: 'mv_h_6', moduleId: 'mastery', target: '하이', translation: 'Hi (casual greeting)' },
    { id: 'mv_h_7', moduleId: 'mastery', target: '호호', translation: 'Ho-ho (laughter)' },
    { id: 'mv_h_8', moduleId: 'mastery', target: '할머니', translation: 'Grandmother' },
    { id: 'mv_h_9', moduleId: 'mastery', target: '하하', translation: 'Ha-ha (laughter)' },
  ],
  ㅜ: [
    { id: 'mv_u_1', moduleId: 'mastery', target: '우리', translation: 'We / Us / Cage (pen)' },
    { id: 'mv_u_2', moduleId: 'mastery', target: '물', translation: 'Water' },
    { id: 'mv_u_3', moduleId: 'mastery', target: '문', translation: 'Door / Gate' },
    { id: 'mv_u_4', moduleId: 'mastery', target: '나무', translation: 'Tree / Wood' },
    { id: 'mv_u_5', moduleId: 'mastery', target: '누나', translation: 'Older sister (used by males)' },
    { id: 'mv_u_6', moduleId: 'mastery', target: '눈', translation: 'Eye / Snow' },
    { id: 'mv_u_7', moduleId: 'mastery', target: '하루', translation: 'One day' },
    { id: 'mv_u_8', moduleId: 'mastery', target: '눈물', translation: 'Tears' },
    { id: 'mv_u_9', moduleId: 'mastery', target: '우물', translation: 'Well (water source)' },
    { id: 'mv_u_10', moduleId: 'mastery', target: '후', translation: 'After / Later' },
    { id: 'mv_u_11', moduleId: 'mastery', target: '무', translation: 'Radish' },
    { id: 'mv_u_12', moduleId: 'mastery', target: '루머', translation: 'Rumor' },
    { id: 'mv_u_13', moduleId: 'mastery', target: '우루루', translation: 'Rushing in a crowd / In a rush' },
  ],
  ㅡ: [
    { id: 'mv_eu_1', moduleId: 'mastery', target: '이름', translation: 'Name' },
    { id: 'mv_eu_2', moduleId: 'mastery', target: '마음', translation: 'Heart / Mind' },
    { id: 'mv_eu_3', moduleId: 'mastery', target: '하늘', translation: 'Sky' },
    { id: 'mv_eu_4', moduleId: 'mastery', target: '흐름', translation: 'Flow / Current' },
    { id: 'mv_eu_5', moduleId: 'mastery', target: '어른', translation: 'Adult / Elder' },
    { id: 'mv_eu_6', moduleId: 'mastery', target: '으음', translation: 'Hmm / Well (pondering sound)' },
    { id: 'mv_eu_7', moduleId: 'mastery', target: '느림', translation: 'Slowness' },
    { id: 'mv_eu_8', moduleId: 'mastery', target: '흐린 날', translation: 'Cloudy day' },
  ],

  // --- Stage 3: Top Row Keys (ㄱ, ㅅ, ㄷ, ㅈ, ㅂ, ㅛ, ㅕ, ㅑ, ㅐ, ㅔ) ---
  ㄱ: [
    { id: 'mv_g_1', moduleId: 'mastery', target: '가구', translation: 'Furniture' },
    { id: 'mv_g_2', moduleId: 'mastery', target: '고기', translation: 'Meat' },
    { id: 'mv_g_3', moduleId: 'mastery', target: '가을', translation: 'Autumn' },
    { id: 'mv_g_4', moduleId: 'mastery', target: '길', translation: 'Road / Street' },
    { id: 'mv_g_5', moduleId: 'mastery', target: '구름', translation: 'Cloud' },
    { id: 'mv_g_6', moduleId: 'mastery', target: '강', translation: 'River' },
    { id: 'mv_g_7', moduleId: 'mastery', target: '감', translation: 'Persimmon / Feeling' },
    { id: 'mv_g_8', moduleId: 'mastery', target: '국', translation: 'Soup / Broth / Nation' },
    { id: 'mv_g_9', moduleId: 'mastery', target: '그림', translation: 'Picture / Drawing' },
  ],
  ㅅ: [
    { id: 'mv_s_1', moduleId: 'mastery', target: '사람', translation: 'Person / Human' },
    { id: 'mv_s_2', moduleId: 'mastery', target: '사랑', translation: 'Love' },
    { id: 'mv_s_3', moduleId: 'mastery', target: '소', translation: 'Cow / Bull' },
    { id: 'mv_s_4', moduleId: 'mastery', target: '손', translation: 'Hand' },
    { id: 'mv_s_5', moduleId: 'mastery', target: '시간', translation: 'Time / Hour' },
    { id: 'mv_s_6', moduleId: 'mastery', target: '소리', translation: 'Sound / Noise' },
    { id: 'mv_s_7', moduleId: 'mastery', target: '산', translation: 'Mountain' },
    { id: 'mv_s_8', moduleId: 'mastery', target: '사슴', translation: 'Deer' },
    { id: 'mv_s_9', moduleId: 'mastery', target: '시소', translation: 'Seesaw' },
  ],
  ㄷ: [
    { id: 'mv_d_1', moduleId: 'mastery', target: '다리', translation: 'Leg / Bridge' },
    { id: 'mv_d_2', moduleId: 'mastery', target: '달', translation: 'Moon / Month' },
    { id: 'mv_d_3', moduleId: 'mastery', target: '돈', translation: 'Money' },
    { id: 'mv_d_4', moduleId: 'mastery', target: '돌', translation: 'Stone / Rock' },
    { id: 'mv_d_5', moduleId: 'mastery', target: '들', translation: 'Field / Plural marker (-s)' },
    { id: 'mv_d_6', moduleId: 'mastery', target: '도마', translation: 'Cutting board' },
    { id: 'mv_d_7', moduleId: 'mastery', target: '도시', translation: 'City' },
    { id: 'mv_d_8', moduleId: 'mastery', target: '두 사람', translation: 'Two people' },
  ],
  ㅈ: [
    { id: 'mv_j_1', moduleId: 'mastery', target: '지도', translation: 'Map' },
    { id: 'mv_j_2', moduleId: 'mastery', target: '자리', translation: 'Seat / Spot' },
    { id: 'mv_j_3', moduleId: 'mastery', target: '잠', translation: 'Sleep' },
    { id: 'mv_j_4', moduleId: 'mastery', target: '주말', translation: 'Weekend' },
    { id: 'mv_j_5', moduleId: 'mastery', target: '자석', translation: 'Magnet' },
    { id: 'mv_j_6', moduleId: 'mastery', target: '자라', translation: 'Softshell turtle / To grow' },
  ],
  ㅂ: [
    { id: 'mv_b_1', moduleId: 'mastery', target: '바다', translation: 'Sea / Ocean' },
    { id: 'mv_b_2', moduleId: 'mastery', target: '밥', translation: 'Rice / Meal' },
    { id: 'mv_b_3', moduleId: 'mastery', target: '발', translation: 'Foot' },
    { id: 'mv_b_4', moduleId: 'mastery', target: '밤', translation: 'Night / Chestnut' },
    { id: 'mv_b_5', moduleId: 'mastery', target: '봄', translation: 'Spring (season)' },
    { id: 'mv_b_6', moduleId: 'mastery', target: '바람', translation: 'Wind / Breeze' },
    { id: 'mv_b_7', moduleId: 'mastery', target: '방', translation: 'Room' },
    { id: 'mv_b_8', moduleId: 'mastery', target: '비', translation: 'Rain' },
    { id: 'mv_b_9', moduleId: 'mastery', target: '집', translation: 'House / Home' },
    { id: 'mv_b_10', moduleId: 'mastery', target: '지갑', translation: 'Wallet' },
  ],
  ㅛ: [
    { id: 'mv_yo_1', moduleId: 'mastery', target: '요리', translation: 'Cooking / Cuisine' },
    { id: 'mv_yo_2', moduleId: 'mastery', target: '교실', translation: 'Classroom' },
    { id: 'mv_yo_3', moduleId: 'mastery', target: '요일', translation: 'Day of the week' },
    { id: 'mv_yo_4', moduleId: 'mastery', target: '요구', translation: 'Demand / Request' },
    { id: 'mv_yo_5', moduleId: 'mastery', target: '음료', translation: 'Beverage / Drink' },
    { id: 'mv_yo_6', moduleId: 'mastery', target: '요람', translation: 'Cradle' },
  ],
  ㅕ: [
    { id: 'mv_yeo_1', moduleId: 'mastery', target: '여기', translation: 'Here' },
    { id: 'mv_yeo_2', moduleId: 'mastery', target: '여름', translation: 'Summer' },
    { id: 'mv_yeo_3', moduleId: 'mastery', target: '여자', translation: 'Woman / Female' },
    { id: 'mv_yeo_4', moduleId: 'mastery', target: '연습', translation: 'Practice' },
    { id: 'mv_yeo_5', moduleId: 'mastery', target: '역', translation: 'Station' },
    { id: 'mv_yeo_6', moduleId: 'mastery', target: '연기', translation: 'Smoke / Acting' },
  ],
  ㅑ: [
    { id: 'mv_ya_1', moduleId: 'mastery', target: '이야기', translation: 'Story / Conversation' },
    { id: 'mv_ya_2', moduleId: 'mastery', target: '야구', translation: 'Baseball' },
    { id: 'mv_ya_3', moduleId: 'mastery', target: '양', translation: 'Sheep / Quantity' },
    { id: 'mv_ya_4', moduleId: 'mastery', target: '약속', translation: 'Promise / Appointment' },
    { id: 'mv_ya_5', moduleId: 'mastery', target: '야경', translation: 'Night view' },
  ],
  ㅐ: [
    { id: 'mv_ae_1', moduleId: 'mastery', target: '노래', translation: 'Song' },
    { id: 'mv_ae_2', moduleId: 'mastery', target: '배', translation: 'Boat / Pear / Stomach' },
    { id: 'mv_ae_3', moduleId: 'mastery', target: '새', translation: 'Bird / New' },
    { id: 'mv_ae_4', moduleId: 'mastery', target: '해', translation: 'Sun / Year' },
    { id: 'mv_ae_5', moduleId: 'mastery', target: '개미', translation: 'Ant' },
    { id: 'mv_ae_6', moduleId: 'mastery', target: '매일', translation: 'Every day' },
    { id: 'mv_ae_7', moduleId: 'mastery', target: '여행', translation: 'Travel / Trip' },
    { id: 'mv_ae_8', moduleId: 'mastery', target: '열매', translation: 'Fruit / Berry' },
  ],
  ㅔ: [
    { id: 'mv_e_1', moduleId: 'mastery', target: '가게', translation: 'Shop / Store' },
    { id: 'mv_e_2', moduleId: 'mastery', target: '베개', translation: 'Pillow' },
    { id: 'mv_e_3', moduleId: 'mastery', target: '세상', translation: 'World / Earth' },
    { id: 'mv_e_4', moduleId: 'mastery', target: '제비', translation: 'Swallow (bird)' },
    { id: 'mv_e_5', moduleId: 'mastery', target: '세금', translation: 'Tax' },
    { id: 'mv_e_6', moduleId: 'mastery', target: '메모', translation: 'Memo' },
  ],

  // --- Stage 4: Bottom Row Keys (ㅋ, ㅌ, ㅊ, ㅍ, ㅠ) ---
  ㅋ: [
    { id: 'mv_k_1', moduleId: 'mastery', target: '코', translation: 'Nose' },
    { id: 'mv_k_2', moduleId: 'mastery', target: '카메라', translation: 'Camera' },
    { id: 'mv_k_3', moduleId: 'mastery', target: '쿠키', translation: 'Cookie' },
    { id: 'mv_k_4', moduleId: 'mastery', target: '카드', translation: 'Card' },
    { id: 'mv_k_5', moduleId: 'mastery', target: '키', translation: 'Height / Key' },
    { id: 'mv_k_6', moduleId: 'mastery', target: '콩', translation: 'Bean / Pea' },
    { id: 'mv_k_7', moduleId: 'mastery', target: '퀴즈', translation: 'Quiz' },
    { id: 'mv_k_8', moduleId: 'mastery', target: '코너', translation: 'Corner' },
    { id: 'mv_k_9', moduleId: 'mastery', target: '콜라', translation: 'Cola' },
    { id: 'mv_k_10', moduleId: 'mastery', target: '코코아', translation: 'Cocoa' },
    { id: 'mv_k_11', moduleId: 'mastery', target: '마스크', translation: 'Mask' },
    { id: 'mv_k_12', moduleId: 'mastery', target: '크기', translation: 'Size / Dimension' },
    { id: 'mv_k_13', moduleId: 'mastery', target: '스키', translation: 'Ski' },
    { id: 'mv_k_14', moduleId: 'mastery', target: '케이크', translation: 'Cake' },
    { id: 'mv_k_15', moduleId: 'mastery', target: '잉크', translation: 'Ink' },
    { id: 'mv_k_16', moduleId: 'mastery', target: '마이크', translation: 'Microphone' },
    { id: 'mv_k_17', moduleId: 'mastery', target: '밀크', translation: 'Milk' },
  ],
  ㅌ: [
    { id: 'mv_t_1', moduleId: 'mastery', target: '토마토', translation: 'Tomato' },
    { id: 'mv_t_2', moduleId: 'mastery', target: '타이어', translation: 'Tire' },
    { id: 'mv_t_3', moduleId: 'mastery', target: '탁자', translation: 'Table / Desk' },
    { id: 'mv_t_4', moduleId: 'mastery', target: '턱', translation: 'Chin / Jaw' },
    { id: 'mv_t_5', moduleId: 'mastery', target: '태양', translation: 'Sun / Solar' },
    { id: 'mv_t_6', moduleId: 'mastery', target: '택시', translation: 'Taxi' },
    { id: 'mv_t_7', moduleId: 'mastery', target: '코트', translation: 'Coat' },
    { id: 'mv_t_8', moduleId: 'mastery', target: '티켓', translation: 'Ticket' },
    { id: 'mv_t_9', moduleId: 'mastery', target: '탈', translation: 'Mask / Trouble' },
    { id: 'mv_t_10', moduleId: 'mastery', target: '타조', translation: 'Ostrich' },
    { id: 'mv_t_11', moduleId: 'mastery', target: '팀', translation: 'Team' },
    { id: 'mv_t_12', moduleId: 'mastery', target: '테니스', translation: 'Tennis' },
    { id: 'mv_t_13', moduleId: 'mastery', target: '도토리', translation: 'Acorn' },
    { id: 'mv_t_14', moduleId: 'mastery', target: '스타', translation: 'Star / Celebrity' },
    { id: 'mv_t_15', moduleId: 'mastery', target: '텐트', translation: 'Tent' },
    { id: 'mv_t_16', moduleId: 'mastery', target: '넥타이', translation: 'Necktie' },
    { id: 'mv_t_17', moduleId: 'mastery', target: '토크', translation: 'Talk / Discussion' },
    { id: 'mv_t_18', moduleId: 'mastery', target: '탱크', translation: 'Tank' },
    { id: 'mv_t_19', moduleId: 'mastery', target: '테크', translation: 'Tech / Technology' },
  ],
  ㅊ: [
    { id: 'mv_ch_1', moduleId: 'mastery', target: '친구', translation: 'Friend' },
    { id: 'mv_ch_2', moduleId: 'mastery', target: '차', translation: 'Car / Tea' },
    { id: 'mv_ch_3', moduleId: 'mastery', target: '책', translation: 'Book' },
    { id: 'mv_ch_4', moduleId: 'mastery', target: '창문', translation: 'Window' },
    { id: 'mv_ch_5', moduleId: 'mastery', target: '치마', translation: 'Skirt' },
    { id: 'mv_ch_6', moduleId: 'mastery', target: '추억', translation: 'Memory / Reminiscence' },
    { id: 'mv_ch_7', moduleId: 'mastery', target: '자동차', translation: 'Automobile / Car' },
    { id: 'mv_ch_8', moduleId: 'mastery', target: '축구', translation: 'Soccer' },
    { id: 'mv_ch_9', moduleId: 'mastery', target: '출발', translation: 'Departure' },
    { id: 'mv_ch_10', moduleId: 'mastery', target: '청춘', translation: 'Youth' },
    { id: 'mv_ch_11', moduleId: 'mastery', target: '치즈', translation: 'Cheese' },
    { id: 'mv_ch_12', moduleId: 'mastery', target: '춤', translation: 'Dance' },
    { id: 'mv_ch_13', moduleId: 'mastery', target: '고추', translation: 'Chili pepper' },
    { id: 'mv_ch_14', moduleId: 'mastery', target: '기차', translation: 'Train' },
    { id: 'mv_ch_15', moduleId: 'mastery', target: '부채', translation: 'Hand fan / Debt' },
    { id: 'mv_ch_16', moduleId: 'mastery', target: '초보', translation: 'Beginner / Novice' },
    { id: 'mv_ch_17', moduleId: 'mastery', target: '추위', translation: 'Cold weather / Chill' },
    { id: 'mv_ch_18', moduleId: 'mastery', target: '치약', translation: 'Toothpaste' },
    { id: 'mv_ch_19', moduleId: 'mastery', target: '초코', translation: 'Chocolate' },
    { id: 'mv_ch_20', moduleId: 'mastery', target: '체크', translation: 'Check' },
  ],
  ㅍ: [
    { id: 'mv_p_1', moduleId: 'mastery', target: '파도', translation: 'Wave / Waves' },
    { id: 'mv_p_2', moduleId: 'mastery', target: '우표', translation: 'Postage stamp' },
    { id: 'mv_p_3', moduleId: 'mastery', target: '포도', translation: 'Grape' },
    { id: 'mv_p_4', moduleId: 'mastery', target: '편지', translation: 'Letter' },
    { id: 'mv_p_5', moduleId: 'mastery', target: '피아노', translation: 'Piano' },
    { id: 'mv_p_6', moduleId: 'mastery', target: '피부', translation: 'Skin' },
    { id: 'mv_p_7', moduleId: 'mastery', target: '커피', translation: 'Coffee' },
    { id: 'mv_p_8', moduleId: 'mastery', target: '풀', translation: 'Grass' },
    { id: 'mv_p_9', moduleId: 'mastery', target: '폭포', translation: 'Waterfall' },
    { id: 'mv_p_10', moduleId: 'mastery', target: '프로', translation: 'Professional / Percent' },
    { id: 'mv_p_11', moduleId: 'mastery', target: '캠프', translation: 'Camp' },
    { id: 'mv_p_12', moduleId: 'mastery', target: '테이프', translation: 'Tape' },
    { id: 'mv_p_13', moduleId: 'mastery', target: '파', translation: 'Green onion / Scallion' },
    { id: 'mv_p_14', moduleId: 'mastery', target: '피자', translation: 'Pizza' },
    { id: 'mv_p_15', moduleId: 'mastery', target: '골프', translation: 'Golf' },
    { id: 'mv_p_16', moduleId: 'mastery', target: '양파', translation: 'Onion' },
    { id: 'mv_p_17', moduleId: 'mastery', target: '수프', translation: 'Soup' },
    { id: 'mv_p_18', moduleId: 'mastery', target: '소풍', translation: 'Picnic / Excursion' },
    { id: 'mv_p_19', moduleId: 'mastery', target: '카페', translation: 'Cafe / Coffee shop' },
    { id: 'mv_p_20', moduleId: 'mastery', target: '포크', translation: 'Fork' },
    { id: 'mv_p_21', moduleId: 'mastery', target: '캠퍼스', translation: 'Campus' },
  ],
  ㅠ: [
    { id: 'mv_yu_1', moduleId: 'mastery', target: '휴지', translation: 'Tissue / Wastepaper' },
    { id: 'mv_yu_2', moduleId: 'mastery', target: '유리', translation: 'Glass' },
    { id: 'mv_yu_3', moduleId: 'mastery', target: '유학', translation: 'Study abroad' },
    { id: 'mv_yu_4', moduleId: 'mastery', target: '뉴스', translation: 'News' },
    { id: 'mv_yu_5', moduleId: 'mastery', target: '휴일', translation: 'Holiday' },
    { id: 'mv_yu_6', moduleId: 'mastery', target: '우유', translation: 'Milk' },
    { id: 'mv_yu_7', moduleId: 'mastery', target: '유명', translation: 'Fame / Renown' },
    { id: 'mv_yu_8', moduleId: 'mastery', target: '유월', translation: 'June' },
    { id: 'mv_yu_9', moduleId: 'mastery', target: '유행', translation: 'Trend / Fashion' },
    { id: 'mv_yu_10', moduleId: 'mastery', target: '휴게소', translation: 'Rest area / Rest stop' },
    { id: 'mv_yu_11', moduleId: 'mastery', target: '유도', translation: 'Judo' },
    { id: 'mv_yu_12', moduleId: 'mastery', target: '유람선', translation: 'Cruise ship / Excursion boat' },
    { id: 'mv_yu_13', moduleId: 'mastery', target: '유적', translation: 'Historic ruins / Relic site' },
    { id: 'mv_yu_14', moduleId: 'mastery', target: '뮤지컬', translation: 'Musical' },
    { id: 'mv_yu_15', moduleId: 'mastery', target: '유치원', translation: 'Kindergarten' },
    { id: 'mv_yu_16', moduleId: 'mastery', target: '휴식', translation: 'Rest / Break / Relaxation' },
    { id: 'mv_yu_17', moduleId: 'mastery', target: '다큐', translation: 'Documentary' },
  ],

  // --- Stage 5: Shift Keys (ㄲ, ㅆ, ㄸ, ㅉ, ㅃ, ㅒ, ㅖ) ---
  ㄲ: [
    { id: 'mv_kk_1', moduleId: 'mastery', target: '까치', translation: 'Magpie' },
    { id: 'mv_kk_2', moduleId: 'mastery', target: '꼬마', translation: 'Little child / Kid' },
    { id: 'mv_kk_3', moduleId: 'mastery', target: '꽃', translation: 'Flower' },
    { id: 'mv_kk_4', moduleId: 'mastery', target: '꿈', translation: 'Dream' },
    { id: 'mv_kk_5', moduleId: 'mastery', target: '까마귀', translation: 'Crow / Raven' },
    { id: 'mv_kk_6', moduleId: 'mastery', target: '꽃병', translation: 'Flower vase' },
    { id: 'mv_kk_7', moduleId: 'mastery', target: '꼭', translation: 'Surely / Exactly / Without fail' },
    { id: 'mv_kk_8', moduleId: 'mastery', target: '깨', translation: 'Sesame' },
    { id: 'mv_kk_9', moduleId: 'mastery', target: '껍질', translation: 'Skin / Peel / Shell' },
    { id: 'mv_kk_10', moduleId: 'mastery', target: '꽃길', translation: 'Flower path' },
    { id: 'mv_kk_11', moduleId: 'mastery', target: '꼬리', translation: 'Tail' },
  ],
  ㅆ: [
    { id: 'mv_ss_1', moduleId: 'mastery', target: '쌀', translation: 'Uncooked rice / Raw rice' },
    { id: 'mv_ss_2', moduleId: 'mastery', target: '싸움', translation: 'Fight / Battle' },
    { id: 'mv_ss_3', moduleId: 'mastery', target: '씨앗', translation: 'Seed' },
    { id: 'mv_ss_4', moduleId: 'mastery', target: '쓰기', translation: 'Writing' },
    { id: 'mv_ss_5', moduleId: 'mastery', target: '쑥', translation: 'Mugwort' },
    { id: 'mv_ss_6', moduleId: 'mastery', target: '씨', translation: 'Seed / Mr. / Ms. (honorific suffix)' },
    { id: 'mv_ss_7', moduleId: 'mastery', target: '쏘다', translation: 'To shoot' },
    { id: 'mv_ss_8', moduleId: 'mastery', target: '썰매', translation: 'Sled' },
    { id: 'mv_ss_9', moduleId: 'mastery', target: '쌍둥이', translation: 'Twins' },
    { id: 'mv_ss_10', moduleId: 'mastery', target: '씨름', translation: 'Korean wrestling' },
    { id: 'mv_ss_11', moduleId: 'mastery', target: '썰다', translation: 'To slice / To chop' },
  ],
  ㄸ: [
    { id: 'mv_tt_1', moduleId: 'mastery', target: '떡', translation: 'Rice cake' },
    { id: 'mv_tt_2', moduleId: 'mastery', target: '딸기', translation: 'Strawberry' },
    { id: 'mv_tt_3', moduleId: 'mastery', target: '땅', translation: 'Land / Ground' },
    { id: 'mv_tt_4', moduleId: 'mastery', target: '땀', translation: 'Sweat' },
    { id: 'mv_tt_5', moduleId: 'mastery', target: '또', translation: 'Again / Also' },
    { id: 'mv_tt_6', moduleId: 'mastery', target: '뚜껑', translation: 'Lid / Cap' },
    { id: 'mv_tt_7', moduleId: 'mastery', target: '뜻', translation: 'Meaning / Will / Intention' },
    { id: 'mv_tt_8', moduleId: 'mastery', target: '뛰다', translation: 'To run / To jump' },
    { id: 'mv_tt_9', moduleId: 'mastery', target: '딸', translation: 'Daughter' },
    { id: 'mv_tt_10', moduleId: 'mastery', target: '또다시', translation: 'Once again' },
    { id: 'mv_tt_11', moduleId: 'mastery', target: '떨림', translation: 'Tremor / Vibration / Quiver' },
  ],
  ㅉ: [
    { id: 'mv_jj_1', moduleId: 'mastery', target: '찌개', translation: 'Stew' },
    { id: 'mv_jj_2', moduleId: 'mastery', target: '짝', translation: 'Pair / Partner' },
    { id: 'mv_jj_3', moduleId: 'mastery', target: '쪽', translation: 'Side / Page / Direction' },
    { id: 'mv_jj_4', moduleId: 'mastery', target: '진짜', translation: 'Really / Real / Genuine' },
    { id: 'mv_jj_5', moduleId: 'mastery', target: '짜장면', translation: 'Black bean noodles' },
    { id: 'mv_jj_6', moduleId: 'mastery', target: '짜다', translation: 'To be salty / To squeeze' },
    { id: 'mv_jj_7', moduleId: 'mastery', target: '찜', translation: 'Steamed dish' },
    { id: 'mv_jj_8', moduleId: 'mastery', target: '쪽지', translation: 'Note / Memo' },
    { id: 'mv_jj_9', moduleId: 'mastery', target: '찌다', translation: 'To steam / To gain weight' },
    { id: 'mv_jj_10', moduleId: 'mastery', target: '짜릿하다', translation: 'To be thrilling' },
  ],
  ㅃ: [
    { id: 'mv_bb_1', moduleId: 'mastery', target: '빵', translation: 'Bread' },
    { id: 'mv_bb_2', moduleId: 'mastery', target: '뼈', translation: 'Bone' },
    { id: 'mv_bb_3', moduleId: 'mastery', target: '뿌리', translation: 'Root' },
    { id: 'mv_bb_4', moduleId: 'mastery', target: '뽀뽀', translation: 'Kiss / Peck' },
    { id: 'mv_bb_5', moduleId: 'mastery', target: '빨래', translation: 'Laundry' },
    { id: 'mv_bb_6', moduleId: 'mastery', target: '빠르다', translation: 'To be fast' },
    { id: 'mv_bb_7', moduleId: 'mastery', target: '뺨', translation: 'Cheek' },
    { id: 'mv_bb_8', moduleId: 'mastery', target: '빨리', translation: 'Quickly' },
    { id: 'mv_bb_9', moduleId: 'mastery', target: '빼다', translation: 'To subtract / To remove' },
    { id: 'mv_bb_10', moduleId: 'mastery', target: '뽐내다', translation: 'To show off / To boast' },
  ],
  ㅒ: [
    { id: 'mv_yae_1', moduleId: 'mastery', target: '얘기', translation: 'Story / Chat' },
    { id: 'mv_yae_2', moduleId: 'mastery', target: '얘들아', translation: 'Children / Hey guys (calling youngsters)' },
    { id: 'mv_yae_3', moduleId: 'mastery', target: '얘', translation: 'This child / Hey (casual call)' },
    { id: 'mv_yae_4', moduleId: 'mastery', target: '얘는', translation: 'This child is / As for this one' },
    { id: 'mv_yae_5', moduleId: 'mastery', target: '얘기하다', translation: 'To talk / To chat' },
    { id: 'mv_yae_6', moduleId: 'mastery', target: '걔', translation: 'That kid / That person (casual)' },
    { id: 'mv_yae_7', moduleId: 'mastery', target: '걔는', translation: 'That kid is / As for that one' },
    { id: 'mv_yae_8', moduleId: 'mastery', target: '쟤', translation: 'That kid over there / That person over there' },
    { id: 'mv_yae_9', moduleId: 'mastery', target: '쟤는', translation: 'That kid over there is' },
    { id: 'mv_yae_10', moduleId: 'mastery', target: '얘기책', translation: 'Storybook' },
    { id: 'mv_yae_11', moduleId: 'mastery', target: '재미난 얘기', translation: 'Fun story' },
    { id: 'mv_yae_12', moduleId: 'mastery', target: '우리 얘기', translation: 'Our story' },
  ],
  ㅖ: [
    { id: 'mv_ye_1', moduleId: 'mastery', target: '예절', translation: 'Manners / Etiquette' },
    { id: 'mv_ye_2', moduleId: 'mastery', target: '시계', translation: 'Clock / Watch' },
    { id: 'mv_ye_3', moduleId: 'mastery', target: '세계', translation: 'World / Globe' },
    { id: 'mv_ye_4', moduleId: 'mastery', target: '예술', translation: 'Art' },
    { id: 'mv_ye_5', moduleId: 'mastery', target: '예약', translation: 'Reservation' },
    { id: 'mv_ye_6', moduleId: 'mastery', target: '예보', translation: 'Forecast' },
    { id: 'mv_ye_7', moduleId: 'mastery', target: '예쁘다', translation: 'To be pretty' },
    { id: 'mv_ye_8', moduleId: 'mastery', target: '예의', translation: 'Politeness / Courtesy' },
    { id: 'mv_ye_9', moduleId: 'mastery', target: '예배', translation: 'Worship service / Church service' },
    { id: 'mv_ye_10', moduleId: 'mastery', target: '옛날얘기', translation: 'Old story / Folktale' },
    { id: 'mv_ye_11', moduleId: 'mastery', target: '예감', translation: 'Premonition / Hunch' },
  ],

  // --- Stage 6: Compound Final Consonants (겹받침) ---
  ㄶ: [
    { id: 'mv_nh_1', moduleId: 'mastery', target: '많다', translation: 'To be many / To be abundant' },
    { id: 'mv_nh_2', moduleId: 'mastery', target: '많이', translation: 'A lot / Many' },
    { id: 'mv_nh_3', moduleId: 'mastery', target: '많음', translation: 'Abundance / Plenty' },
    { id: 'mv_nh_4', moduleId: 'mastery', target: '않다', translation: 'To not do / To not be' },
    { id: 'mv_nh_5', moduleId: 'mastery', target: '않아요', translation: 'Do not / Does not' },
    { id: 'mv_nh_6', moduleId: 'mastery', target: '않음', translation: 'Negation / Not doing' },
    { id: 'mv_nh_7', moduleId: 'mastery', target: '괜찮다', translation: 'To be okay / To be fine' },
    { id: 'mv_nh_8', moduleId: 'mastery', target: '괜찮아요', translation: 'It is okay / I am fine' },
    {
      id: 'mv_nh_9',
      moduleId: 'mastery',
      target: '귀찮다',
      translation: 'To be tiresome / To be bothersome',
    },
    {
      id: 'mv_nh_10',
      moduleId: 'mastery',
      target: '점잖다',
      translation: 'To be gentle / To be dignified',
    },
    { id: 'mv_nh_11', moduleId: 'mastery', target: '하찮다', translation: 'To be trivial / To be insignificant' },
  ],
  ㄵ: [
    { id: 'mv_nj_1', moduleId: 'mastery', target: '앉다', translation: 'To sit / To sit down' },
    { id: 'mv_nj_2', moduleId: 'mastery', target: '앉아', translation: 'Sit down (casual imperative)' },
    { id: 'mv_nj_3', moduleId: 'mastery', target: '앉아요', translation: 'Please sit down' },
    { id: 'mv_nj_4', moduleId: 'mastery', target: '앉음', translation: 'Sitting (nominal form)' },
    { id: 'mv_nj_5', moduleId: 'mastery', target: '앉히다', translation: 'To seat someone / To sit someone down' },
    {
      id: 'mv_nj_6',
      moduleId: 'mastery',
      target: '걸터앉다',
      translation: 'To perch / To sit astride',
    },
    { id: 'mv_nj_7', moduleId: 'mastery', target: '얹다', translation: 'To place on top / To put on' },
    { id: 'mv_nj_8', moduleId: 'mastery', target: '얹어', translation: 'Place on top (casual imperative)' },
    { id: 'mv_nj_9', moduleId: 'mastery', target: '얹어요', translation: 'Place on top (polite)' },
    { id: 'mv_nj_10', moduleId: 'mastery', target: '얹히다', translation: 'To be placed on top / To have indigestion' },
  ],
  ㄺ: [
    { id: 'mv_lg_1', moduleId: 'mastery', target: '읽다', translation: 'To read' },
    { id: 'mv_lg_2', moduleId: 'mastery', target: '읽어요', translation: 'Read / Reading (polite)' },
    { id: 'mv_lg_3', moduleId: 'mastery', target: '읽기', translation: 'Reading' },
    { id: 'mv_lg_4', moduleId: 'mastery', target: '읽음', translation: 'Reading / Read (nominal form)' },
    { id: 'mv_lg_5', moduleId: 'mastery', target: '닭', translation: 'Chicken' },
    { id: 'mv_lg_6', moduleId: 'mastery', target: '닭고기', translation: 'Chicken meat' },
    { id: 'mv_lg_7', moduleId: 'mastery', target: '통닭', translation: 'Whole roast chicken' },
    { id: 'mv_lg_8', moduleId: 'mastery', target: '맑다', translation: 'To be clear / To be pure' },
    { id: 'mv_lg_9', moduleId: 'mastery', target: '맑은', translation: 'Clear / Pure' },
    { id: 'mv_lg_10', moduleId: 'mastery', target: '맑음', translation: 'Clear (weather)' },
    { id: 'mv_lg_11', moduleId: 'mastery', target: '흙', translation: 'Soil / Earth / Dirt' },
    { id: 'mv_lg_12', moduleId: 'mastery', target: '흙길', translation: 'Dirt path / Unpaved road' },
    { id: 'mv_lg_13', moduleId: 'mastery', target: '붉다', translation: 'To be red / To be crimson' },
    { id: 'mv_lg_14', moduleId: 'mastery', target: '붉은', translation: 'Red / Crimson' },
    { id: 'mv_lg_15', moduleId: 'mastery', target: '밝다', translation: 'To be bright / To dawn' },
    { id: 'mv_lg_16', moduleId: 'mastery', target: '밝은', translation: 'Bright / Radiant' },
    { id: 'mv_lg_17', moduleId: 'mastery', target: '굵다', translation: 'To be thick / To be stout' },
    { id: 'mv_lg_18', moduleId: 'mastery', target: '굵은', translation: 'Thick / Bold' },
    { id: 'mv_lg_19', moduleId: 'mastery', target: '긁다', translation: 'To scratch / To scrape' },
    { id: 'mv_lg_20', moduleId: 'mastery', target: '늙다', translation: 'To grow old / To age' },
  ],
  ㄻ: [
    { id: 'mv_lm_1', moduleId: 'mastery', target: '삶', translation: 'Life' },
    { id: 'mv_lm_2', moduleId: 'mastery', target: '삶다', translation: 'To boil / To simmer' },
    { id: 'mv_lm_3', moduleId: 'mastery', target: '젊다', translation: 'To be young / To be youthful' },
    { id: 'mv_lm_4', moduleId: 'mastery', target: '젊음', translation: 'Youth / Youthfulness' },
    { id: 'mv_lm_5', moduleId: 'mastery', target: '젊은이', translation: 'Young person / Youth' },
    { id: 'mv_lm_6', moduleId: 'mastery', target: '굶다', translation: 'To starve / To skip a meal' },
    { id: 'mv_lm_7', moduleId: 'mastery', target: '굶주림', translation: 'Starvation / Hunger' },
    { id: 'mv_lm_8', moduleId: 'mastery', target: '닮다', translation: 'To resemble / To look like' },
    { id: 'mv_lm_9', moduleId: 'mastery', target: '닮음', translation: 'Resemblance / Similarity' },
    { id: 'mv_lm_10', moduleId: 'mastery', target: '옮다', translation: 'To catch (disease) / To be infected' },
    { id: 'mv_lm_11', moduleId: 'mastery', target: '옮기다', translation: 'To move / To transfer' },
    { id: 'mv_lm_12', moduleId: 'mastery', target: '앎', translation: 'Knowledge / Knowing' },
  ],
  ㄼ: [
    { id: 'mv_lb_1', moduleId: 'mastery', target: '넓다', translation: 'To be spacious / To be wide' },
    { id: 'mv_lb_2', moduleId: 'mastery', target: '넓은', translation: 'Spacious / Broad / Wide' },
    { id: 'mv_lb_3', moduleId: 'mastery', target: '넓이', translation: 'Area / Width' },
    { id: 'mv_lb_4', moduleId: 'mastery', target: '넓히다', translation: 'To widen / To expand' },
    { id: 'mv_lb_5', moduleId: 'mastery', target: '여덟', translation: 'Eight' },
    { id: 'mv_lb_6', moduleId: 'mastery', target: '여덟째', translation: 'Eighth' },
    { id: 'mv_lb_7', moduleId: 'mastery', target: '밟다', translation: 'To step on / To tread' },
    { id: 'mv_lb_8', moduleId: 'mastery', target: '밟아요', translation: 'Step on / Tread (polite)' },
    { id: 'mv_lb_9', moduleId: 'mastery', target: '짧다', translation: 'To be short / To be brief' },
    { id: 'mv_lb_10', moduleId: 'mastery', target: '짧은', translation: 'Short / Brief' },
    { id: 'mv_lb_11', moduleId: 'mastery', target: '얇다', translation: 'To be thin' },
    { id: 'mv_lb_12', moduleId: 'mastery', target: '얇은', translation: 'Thin (sheet / layer)' },
  ],
  ㅄ: [
    { id: 'mv_bs_1', moduleId: 'mastery', target: '없다', translation: 'To not exist / To not have' },
    { id: 'mv_bs_2', moduleId: 'mastery', target: '없어요', translation: 'There is none / Does not exist' },
    { id: 'mv_bs_3', moduleId: 'mastery', target: '없음', translation: 'None / Absence' },
    { id: 'mv_bs_4', moduleId: 'mastery', target: '값', translation: 'Price / Value' },
    { id: 'mv_bs_5', moduleId: 'mastery', target: '값싸다', translation: 'To be cheap / To be inexpensive' },
    { id: 'mv_bs_6', moduleId: 'mastery', target: '값비싸다', translation: 'To be expensive / To be costly' },
    { id: 'mv_bs_7', moduleId: 'mastery', target: '값진', translation: 'Priceless / Valuable' },
    { id: 'mv_bs_8', moduleId: 'mastery', target: '헐값', translation: 'Dirt-cheap price / Bargain price' },
    { id: 'mv_bs_9', moduleId: 'mastery', target: '몸값', translation: 'Ransom / One’s worth' },
    { id: 'mv_bs_10', moduleId: 'mastery', target: '가없다', translation: 'Boundless / Endless' },
  ],
  ㅀ: [
    { id: 'mv_lh_1', moduleId: 'mastery', target: '잃다', translation: 'To lose / To forfeit' },
    { id: 'mv_lh_2', moduleId: 'mastery', target: '잃어버리다', translation: 'To lose / To misplace' },
    { id: 'mv_lh_3', moduleId: 'mastery', target: '잃음', translation: 'Loss' },
    { id: 'mv_lh_4', moduleId: 'mastery', target: '싫다', translation: 'To dislike / To be undesirable' },
    { id: 'mv_lh_5', moduleId: 'mastery', target: '싫어요', translation: 'I dislike it / No, I do not want to' },
    { id: 'mv_lh_6', moduleId: 'mastery', target: '싫음', translation: 'Dislike / Aversion' },
    { id: 'mv_lh_7', moduleId: 'mastery', target: '옳다', translation: 'To be right / To be correct' },
    { id: 'mv_lh_8', moduleId: 'mastery', target: '옳은', translation: 'Right / Just / Proper' },
    { id: 'mv_lh_9', moduleId: 'mastery', target: '옳고 그름', translation: 'Right and wrong' },
    { id: 'mv_lh_10', moduleId: 'mastery', target: '끓다', translation: 'To boil / To seethe' },
    { id: 'mv_lh_11', moduleId: 'mastery', target: '끓이다', translation: 'To boil / To cook (soup or water)' },
    { id: 'mv_lh_12', moduleId: 'mastery', target: '닳다', translation: 'To wear out / To be worn down' },
  ],
  ㄳ: [
    { id: 'mv_gs_1', moduleId: 'mastery', target: '몫', translation: 'Share / Portion' },
    { id: 'mv_gs_2', moduleId: 'mastery', target: '제 몫', translation: 'One’s own share' },
    { id: 'mv_gs_3', moduleId: 'mastery', target: '몫을 하다', translation: 'To do one’s part / To pull one’s weight' },
    { id: 'mv_gs_4', moduleId: 'mastery', target: '삯', translation: 'Wages / Fare / Fee' },
    { id: 'mv_gs_5', moduleId: 'mastery', target: '품삯', translation: 'Day-labor wage / Labor pay' },
    { id: 'mv_gs_6', moduleId: 'mastery', target: '길삯', translation: 'Travel fare / Passage fee' },
    { id: 'mv_gs_7', moduleId: 'mastery', target: '뱃삯', translation: 'Boat fare / Ferry fee' },
    { id: 'mv_gs_8', moduleId: 'mastery', target: '차삯', translation: 'Vehicle fare / Bus fare' },
    { id: 'mv_gs_9', moduleId: 'mastery', target: '일삯', translation: 'Daily wage / Day-labor pay' },
    { id: 'mv_gs_10', moduleId: 'mastery', target: '넋', translation: 'Soul / Spirit' },
    {
      id: 'mv_gs_11',
      moduleId: 'mastery',
      target: '넋두리',
      translation: 'Lamentation / Grumbling complaint',
    },
    {
      id: 'mv_gs_12',
      moduleId: 'mastery',
      target: '넋을 잃다',
      translation: 'To be stunned / To be entranced',
    },
  ],
  ㄾ: [
    { id: 'mv_lt_1', moduleId: 'mastery', target: '핥다', translation: 'To lick / To lap up' },
    { id: 'mv_lt_2', moduleId: 'mastery', target: '핥아요', translation: 'Licks / Licking (polite)' },
    { id: 'mv_lt_3', moduleId: 'mastery', target: '핥아 먹다', translation: 'To lap up / To lick and eat' },
    { id: 'mv_lt_4', moduleId: 'mastery', target: '핥음', translation: 'Licking (nominal form)' },
    { id: 'mv_lt_5', moduleId: 'mastery', target: '핥기', translation: 'Licking action' },
    { id: 'mv_lt_6', moduleId: 'mastery', target: '훑다', translation: 'To skim / To scan / To browse through' },
    { id: 'mv_lt_7', moduleId: 'mastery', target: '훑어요', translation: 'Skims / Scans (polite)' },
    {
      id: 'mv_lt_8',
      moduleId: 'mastery',
      target: '훑어보다',
      translation: 'To glance over / To skim through',
    },
    { id: 'mv_lt_9', moduleId: 'mastery', target: '훑기', translation: 'Skimming / Scanning' },
    {
      id: 'mv_lt_10',
      moduleId: 'mastery',
      target: '훑어내다',
      translation: 'To strip off / To weed out',
    },
    { id: 'mv_lt_11', moduleId: 'mastery', target: '훑어 읽다', translation: 'To skim-read / To browse through' },
  ],
  ㄿ: [
    { id: 'mv_lp_1', moduleId: 'mastery', target: '읊다', translation: 'To recite (poetry) / To chant' },
    { id: 'mv_lp_2', moduleId: 'mastery', target: '읊어요', translation: 'Recites / Chants (polite)' },
    { id: 'mv_lp_3', moduleId: 'mastery', target: '읊조리다', translation: 'To murmur a poem / To chant softly' },
    { id: 'mv_lp_4', moduleId: 'mastery', target: '읊조림', translation: 'Poetic murmuring / Soft chanting' },
    { id: 'mv_lp_5', moduleId: 'mastery', target: '시를 읊다', translation: 'To recite a poem' },
    { id: 'mv_lp_6', moduleId: 'mastery', target: '시를 읊어요', translation: 'Reciting a poem (polite)' },
    { id: 'mv_lp_7', moduleId: 'mastery', target: '노래를 읊다', translation: 'To chant a song / To sing a tune' },
    { id: 'mv_lp_8', moduleId: 'mastery', target: '읊는 소리', translation: 'Sound of reciting poetry' },
    { id: 'mv_lp_9', moduleId: 'mastery', target: '읊기', translation: 'Poetry recitation' },
    { id: 'mv_lp_10', moduleId: 'mastery', target: '읊어보다', translation: 'To try reciting (poetry)' },
    { id: 'mv_lp_11', moduleId: 'mastery', target: '되읊다', translation: 'To recite again / To repeat poetry' },
  ],
  ㄽ: [
    { id: 'mv_ls_1', moduleId: 'mastery', target: '외곬', translation: 'Single-minded path / Dedicated channel' },
    { id: 'mv_ls_2', moduleId: 'mastery', target: '외곬수', translation: 'Single-minded person' },
    {
      id: 'mv_ls_3',
      moduleId: 'mastery',
      target: '외곬으로',
      translation: 'Steadfastly / In a single direction',
    },
    {
      id: 'mv_ls_4',
      moduleId: 'mastery',
      target: '외곬 인생',
      translation: 'Single-minded devotion in life',
    },
    { id: 'mv_ls_5', moduleId: 'mastery', target: '외곬 길', translation: 'Single dedicated path / One-way route' },
    {
      id: 'mv_ls_6',
      moduleId: 'mastery',
      target: '외곬 마음',
      translation: 'Devoted unswerving heart',
    },
    {
      id: 'mv_ls_7',
      moduleId: 'mastery',
      target: '외곬 생각',
      translation: 'Single-minded thought',
    },
    {
      id: 'mv_ls_8',
      moduleId: 'mastery',
      target: '외곬 사랑',
      translation: 'Steadfast undivided love',
    },
    {
      id: 'mv_ls_9',
      moduleId: 'mastery',
      target: '외곬 열정',
      translation: 'Unwavering single passion',
    },
    {
      id: 'mv_ls_10',
      moduleId: 'mastery',
      target: '한 외곬',
      translation: 'A single focused path',
    },
    { id: 'mv_ls_11', moduleId: 'mastery', target: '외곬 삶', translation: 'Single-minded life' },
  ],
};

/**
 * Curated sentence banks for each Sentence Milestone Checkpoint.
 * Every sentence is verified to contain only letters unlocked up to that milestone.
 */
export const MASTERY_CHECKPOINT_SENTENCES: Record<string, LessonItem[]> = {
  // Checkpoint 1: Home Row Sentences (ㅓ, ㅏ, ㅇ, ㄹ, ㅗ, ㅣ, ㅁ, ㄴ, ㅎ, ㅜ, ㅡ)
  cp_home_row: [
    { id: 'cp1_1', moduleId: 'mastery', target: '어머니와 아이', translation: 'Mother and child' },
    {
      id: 'cp1_2',
      moduleId: 'mastery',
      target: '우리 어머니와 누나',
      translation: 'Our mother and older sister',
    },
    {
      id: 'cp1_3',
      moduleId: 'mastery',
      target: '나무 위로 날아오르나',
      translation: 'Does it fly up above the tree?',
    },
    {
      id: 'cp1_4',
      moduleId: 'mastery',
      target: '하늘 위로 흐르는 물',
      translation: 'Water flowing skyward',
    },
    { id: 'cp1_5', moduleId: 'mastery', target: '이름은 하나', translation: 'The name is one' },
    {
      id: 'cp1_6',
      moduleId: 'mastery',
      target: '눈물이 흐르는 날',
      translation: 'A day when tears flow',
    },
    {
      id: 'cp1_7',
      moduleId: 'mastery',
      target: '너와 나의 마음',
      translation: 'Your heart and mine',
    },
    {
      id: 'cp1_8',
      moduleId: 'mastery',
      target: '하나 모아 우리 마음',
      translation: 'Gathering together, our hearts as one',
    },
    {
      id: 'cp1_9',
      moduleId: 'mastery',
      target: '어머니 마음은 하늘',
      translation: 'Mother’s heart is the sky',
    },
    {
      id: 'cp1_10',
      moduleId: 'mastery',
      target: '눈물 어린 너의 눈',
      translation: 'Your tearful eyes',
    },
    {
      id: 'cp1_11',
      moduleId: 'mastery',
      target: '물 위로 흐르는 하루',
      translation: 'A day flowing upon the water',
    },
    {
      id: 'cp1_12',
      moduleId: 'mastery',
      target: '하루하루 늘어나는 힘',
      translation: 'Strength increasing day by day',
    },
    {
      id: 'cp1_13',
      moduleId: 'mastery',
      target: '머리 위로 오른 은하',
      translation: 'The Milky Way rising above our heads',
    },
    {
      id: 'cp1_14',
      moduleId: 'mastery',
      target: '우리 모아 하나로',
      translation: 'Bringing us together as one',
    },
    {
      id: 'cp1_15',
      moduleId: 'mastery',
      target: '너와 나 우리 나라',
      translation: 'You and me, our nation',
    },
    {
      id: 'cp1_16',
      moduleId: 'mastery',
      target: '이마 위로 흐르는 눈물',
      translation: 'Tears flowing down the forehead',
    },
    {
      id: 'cp1_17',
      moduleId: 'mastery',
      target: '얼마나 멀리 오나',
      translation: 'How far has it come?',
    },
    {
      id: 'cp1_18',
      moduleId: 'mastery',
      target: '마음으로 알리는 말',
      translation: 'Words communicated from the heart',
    },
    {
      id: 'cp1_19',
      moduleId: 'mastery',
      target: '어린 아이의 울음',
      translation: 'The crying of a little child',
    },
    {
      id: 'cp1_20',
      moduleId: 'mastery',
      target: '오늘 하루 힘을 모아',
      translation: 'Gathering strength for today',
    },
  ],

  // Checkpoint 2: Top + Home Row Sentences (+ ㄱ, ㅅ, ㄷ, ㅈ, ㅂ, ㅛ, ㅕ, ㅑ, ㅐ, ㅔ)
  cp_top_row: [
    {
      id: 'cp2_1',
      moduleId: 'mastery',
      target: '별을 노래하는 마음으로',
      translation: 'With a heart singing to the stars',
      attribution: '윤동주, <서시> (1941)',
    },
    {
      id: 'cp2_2',
      moduleId: 'mastery',
      target: '엄마야 누나야 강변 살자',
      translation: 'Mom and sister, let’s live by the riverside',
      attribution: '김소월, <엄마야 누나야> (1922)',
    },
    {
      id: 'cp2_3',
      moduleId: 'mastery',
      target: '나의 별에도 봄이 오면',
      translation: 'When spring comes to my star too',
      attribution: '윤동주, <별 헤는 밤> (1941)',
    },
    {
      id: 'cp2_4',
      moduleId: 'mastery',
      target: '가슴 속에 하나 둘 새겨지는 별',
      translation: 'Stars engraved one by one in my heart',
      attribution: '윤동주, <별 헤는 밤> (1941)',
    },
    {
      id: 'cp2_5',
      moduleId: 'mastery',
      target: '사랑도 사람의 일이라',
      translation: 'Love too is a human affair',
      attribution: '한용운, <님의 침묵> (1926)',
    },
    {
      id: 'cp2_6',
      moduleId: 'mastery',
      target: '동짓달 기나긴 밤을 한 허리를 베어 내어',
      translation: 'Cutting out the waist of the long winter night',
      attribution: '황진이, 시조 (16세기)',
    },
    {
      id: 'cp2_7',
      moduleId: 'mastery',
      target: '가을 바람이 시원해요',
      translation: 'The autumn breeze is refreshing',
    },
    {
      id: 'cp2_8',
      moduleId: 'mastery',
      target: '바다로 여행을 가요',
      translation: 'Let’s go on a trip to the sea',
    },
    {
      id: 'cp2_9',
      moduleId: 'mastery',
      target: '오늘 저녁에 밥을 먹어요',
      translation: 'Having dinner this evening',
    },
    {
      id: 'cp2_10',
      moduleId: 'mastery',
      target: '이웃과 재미난 이야기를 해요',
      translation: 'Chatting about fun stories with a neighbor',
    },
    {
      id: 'cp2_11',
      moduleId: 'mastery',
      target: '일어나서 운동을 해요',
      translation: 'Wake up and exercise',
    },
    {
      id: 'cp2_12',
      moduleId: 'mastery',
      target: '새로운 노래를 들어요',
      translation: 'Listen to a new song',
    },
    {
      id: 'cp2_13',
      moduleId: 'mastery',
      target: '가게에서 맛난 음식을 사요',
      translation: 'Buy delicious food at the store',
    },
    {
      id: 'cp2_14',
      moduleId: 'mastery',
      target: '도서관에서 조용히 공부해요',
      translation: 'Study quietly in the library',
    },
    {
      id: 'cp2_15',
      moduleId: 'mastery',
      target: '사랑하는 가족과 모여 살아요',
      translation: 'Live together with beloved family',
    },
    {
      id: 'cp2_16',
      moduleId: 'mastery',
      target: '주말에 시원한 바람을 맞아요',
      translation: 'Feel the cool breeze on the weekend',
    },
    {
      id: 'cp2_17',
      moduleId: 'mastery',
      target: '밤하늘에 아름다운 별을 봐요',
      translation: 'Look at beautiful stars in the night sky',
    },
    {
      id: 'cp2_18',
      moduleId: 'mastery',
      target: '매일 조금 더 발전하는 나',
      translation: 'Myself improving a little more every day',
    },
    {
      id: 'cp2_19',
      moduleId: 'mastery',
      target: '세상 곳곳을 여행하며 살아요',
      translation: 'Traveling all over the world and living life',
    },
    {
      id: 'cp2_20',
      moduleId: 'mastery',
      target: '여름 바닷가에서 수영을 해요',
      translation: 'Swim at the summer beach',
    },
  ],

  // Checkpoint 3: Full Alphabet Sentences (+ ㅋ, ㅌ, ㅊ, ㅍ, ㅠ)
  cp_bottom_row: [
    {
      id: 'cp3_1',
      moduleId: 'mastery',
      target: '청포도 익어가는 내 고장 칠월은',
      translation: 'July in my hometown when green grapes ripen',
      attribution: '이육사, <청포도> (1939)',
    },
    {
      id: 'cp3_2',
      moduleId: 'mastery',
      target: '하늘 아래 푸른 바다가 가슴을 열고',
      translation: 'Under the sky the blue ocean opens its heart',
      attribution: '이육사, <청포도> (1939)',
    },
    {
      id: 'cp3_3',
      moduleId: 'mastery',
      target: '향단아 그네 줄을 밀어라, 서으로 가는 달같이',
      translation: 'Hyangdan, push the swing ropes, like the moon moving west',
      attribution: '서정주, <추천사> (1956)',
    },
    {
      id: 'cp3_4',
      moduleId: 'mastery',
      target: '푸른 하늘에 퍼지는 은은한 종소리',
      translation: 'Gentle bell toll spreading through the blue sky',
    },
    {
      id: 'cp3_5',
      moduleId: 'mastery',
      target: '시원한 커피 한 잔의 여유',
      translation: 'Relaxing with a cup of cool coffee',
    },
    {
      id: 'cp3_6',
      moduleId: 'mastery',
      target: '기차를 타고 여행을 가요',
      translation: 'Take a train and go on a trip',
    },
    {
      id: 'cp3_7',
      moduleId: 'mastery',
      target: '친구에게 보낼 편지를 적어요',
      translation: 'Write a letter to send to a friend',
    },
    {
      id: 'cp3_8',
      moduleId: 'mastery',
      target: '달콤한 포도와 토마토를 먹어요',
      translation: 'Eat sweet grapes and tomatoes',
    },
    {
      id: 'cp3_9',
      moduleId: 'mastery',
      target: '창문을 열고 시원한 공기를 마셔요',
      translation: 'Open the window and breathe cool air',
    },
    {
      id: 'cp3_10',
      moduleId: 'mastery',
      target: '피아노 소리가 아름답게 울려요',
      translation: 'The piano sound echoes beautifully',
    },
    {
      id: 'cp3_11',
      moduleId: 'mastery',
      target: '휴일에 집에서 푹 쉬어요',
      translation: 'Rest comfortably at home on the holiday',
    },
    {
      id: 'cp3_12',
      moduleId: 'mastery',
      target: '택시를 타고 공항으로 가요',
      translation: 'Take a taxi to the airport',
    },
    {
      id: 'cp3_13',
      moduleId: 'mastery',
      target: '책을 보며 깊은 생각에 잠겨요',
      translation: 'Reading a book and getting lost in deep thought',
    },
    {
      id: 'cp3_14',
      moduleId: 'mastery',
      target: '카메라로 추억을 사진에 담아요',
      translation: 'Capture memories in photos with a camera',
    },
    {
      id: 'cp3_15',
      moduleId: 'mastery',
      target: '파도가 밀려오는 해변을 걸어요',
      translation: 'Walk along the beach where waves roll in',
    },
    {
      id: 'cp3_16',
      moduleId: 'mastery',
      target: '우체국에서 편지에 우표를 붙여요',
      translation: 'Stick a postage stamp on the letter at the post office',
    },
    {
      id: 'cp3_17',
      moduleId: 'mastery',
      target: '치마를 입고 외출을 준비해요',
      translation: 'Put on a skirt and prepare to go out',
    },
    {
      id: 'cp3_18',
      moduleId: 'mastery',
      target: '탁자 위에 커피잔을 놓아요',
      translation: 'Place the coffee cup on the table',
    },
    {
      id: 'cp3_19',
      moduleId: 'mastery',
      target: '신나는 음악에 맞춰 춤을 춰요',
      translation: 'Dance in rhythm to exciting music',
    },
    {
      id: 'cp3_20',
      moduleId: 'mastery',
      target: '기차를 타고 푸른 바다로 가요',
      translation: 'Take a train and go to the blue ocean',
    },
    {
      id: 'cp3_21',
      moduleId: 'mastery',
      target: '탁자 위에 향기로운 커피를 놓아요',
      translation: 'Place fragrant coffee upon the table',
    },
    {
      id: 'cp3_22',
      moduleId: 'mastery',
      target: '휴일에는 친구와 영화를 보며 쉬어요',
      translation: 'Rest on holidays watching movies with a friend',
    },
    {
      id: 'cp3_23',
      moduleId: 'mastery',
      target: '카메라에 담긴 소중한 추억들',
      translation: 'Precious memories captured on the camera',
    },
    {
      id: 'cp3_24',
      moduleId: 'mastery',
      target: '시원한 파도 소리를 들으며 해변을 걸어요',
      translation: 'Walk along the beach listening to the sound of cool waves',
    },
    {
      id: 'cp3_25',
      moduleId: 'mastery',
      target: '우체국에 들러 친구에게 편지를 보내요',
      translation: 'Stop by the post office to send a letter to a friend',
    },
  ],

  // Checkpoint 4: Shift Key Sentences (+ ㄲ, ㅆ, ㄸ, ㅉ, ㅃ, ㅒ, ㅖ)
  cp_shift_keys: [
    {
      id: 'cp4_1',
      moduleId: 'mastery',
      target: '잎새에 이는 바람에도 나는 괴로워했다',
      translation: 'Even in the wind stirring the leaves, I felt torment',
      attribution: '윤동주, <서시> (1941)',
    },
    {
      id: 'cp4_2',
      moduleId: 'mastery',
      target: '별 하나에 쓸쓸함과 별 하나에 동경과',
      translation: 'Loneliness in one star, longing in another',
      attribution: '윤동주, <별 헤는 밤> (1941)',
    },
    {
      id: 'cp4_3',
      moduleId: 'mastery',
      target: '별 하나에 아름다운 말 한마디씩 불러봅니다',
      translation: 'Calling out beautiful words one by one for each star',
      attribution: '윤동주, <별 헤는 밤> (1941)',
    },
    {
      id: 'cp4_4',
      moduleId: 'mastery',
      target: '영변에 약산 진달래꽃, 아름 따다 가실 길에 뿌리우리다',
      translation: 'Azaleas of Yaksan, I will scatter armfuls along your path',
      attribution: '김소월, <진달래꽃> (1925)',
    },
    {
      id: 'cp4_5',
      moduleId: 'mastery',
      target: '아아, 님은 갔지마는 나는 님을 보내지 아니하였습니다',
      translation: 'Ah, my beloved has gone, but I have not let you go',
      attribution: '한용운, <님의 침묵> (1926)',
    },
    {
      id: 'cp4_6',
      moduleId: 'mastery',
      target: '뜰에는 반짝이는 금모래빛, 강변의 노래',
      translation: 'In the courtyard sparkling golden sand, riverside melody',
      attribution: '김소월, <엄마야 누나야> (1922)',
    },
    {
      id: 'cp4_7',
      moduleId: 'mastery',
      target: '그곳이 차마 꿈엔들 잊힐리야',
      translation: 'Could that place ever be forgotten, even in dreams',
      attribution: '정지용, <향수> (1927)',
    },
    {
      id: 'cp4_8',
      moduleId: 'mastery',
      target: '언제나 따뜻한 사랑으로 서로를 아껴주세요',
      translation: 'Always cherish each other with warm love',
    },
    {
      id: 'cp4_9',
      moduleId: 'mastery',
      target: '꽃집에서 예쁜 꽃을 골라요',
      translation: 'Pick pretty flowers at the florist',
    },
    {
      id: 'cp4_10',
      moduleId: 'mastery',
      target: '뚝배기에 보글보글 맛있는 찌개',
      translation: 'Delicious stew bubbling in an earthenware pot',
    },
    {
      id: 'cp4_11',
      moduleId: 'mastery',
      target: '갓 구운 따끈따끈한 빵 냄새',
      translation: 'Aroma of freshly baked warm bread',
    },
    {
      id: 'cp4_12',
      moduleId: 'mastery',
      target: '딸기잼을 바른 토스트를 먹어요',
      translation: 'Eat toast spread with strawberry jam',
    },
    {
      id: 'cp4_13',
      moduleId: 'mastery',
      target: '진짜 재미있는 옛날이야기',
      translation: 'A truly fascinating old folktale',
    },
    {
      id: 'cp4_14',
      moduleId: 'mastery',
      target: '시계를 보며 약속 시간을 지켜요',
      translation: 'Check the clock and keep the appointment on time',
    },
    {
      id: 'cp4_15',
      moduleId: 'mastery',
      target: '꿈을 향해 한 걸음씩 나아가요',
      translation: 'Step forward toward your dreams',
    },
    {
      id: 'cp4_16',
      moduleId: 'mastery',
      target: '손을 깨끗이 씻고 식사할 준비를 해요',
      translation: 'Wash hands clean and get ready for the meal',
    },
    {
      id: 'cp4_17',
      moduleId: 'mastery',
      target: '날씨 예보를 미리 확인해요',
      translation: 'Check the weather forecast in advance',
    },
    {
      id: 'cp4_18',
      moduleId: 'mastery',
      target: '친구와 함께 나누는 즐거운 얘기',
      translation: 'A pleasant conversation shared with a friend',
    },
    {
      id: 'cp4_19',
      moduleId: 'mastery',
      target: '빨래를 널고 햇살을 만끽해요',
      translation: 'Hang out the laundry and enjoy the sunshine',
    },
    {
      id: 'cp4_20',
      moduleId: 'mastery',
      target: '꼬마 아이가 활짝 웃고 있어요',
      translation: 'The little child is smiling brightly',
    },
  ],

  // Checkpoint 5: Master Review & Complex Passages (+ Compound Batchim)
  cp_master: [
    {
      id: 'cp5_1',
      moduleId: 'mastery',
      target: '사람마다 하여금 쉽게 익혀 날마다 씀에 편안케 하고자 할 따름이니라',
      translation: 'Wishing only that everyone learn easily and use comfortably every day',
      attribution: '세종대왕, <훈민정음 어제 서문> (1446)',
    },
    {
      id: 'cp5_2',
      moduleId: 'mastery',
      target: '죽는 날까지 하늘을 우러러 한 점 부끄럼이 없기를',
      translation: 'Wishing until my dying day to look up without a speck of shame',
      attribution: '윤동주, <서시> (1941)',
    },
    {
      id: 'cp5_3',
      moduleId: 'mastery',
      target: '그리고 나한테 주어진 길을 걸어가야겠다',
      translation: 'And I must walk the path given unto me',
      attribution: '윤동주, <서시> (1941)',
    },
    {
      id: 'cp5_4',
      moduleId: 'mastery',
      target: '나 보기가 역겨워 가실 때에는 말없이 고이 보내 드리우리다',
      translation: 'When you leave weary of seeing me, I will quietly let you go',
      attribution: '김소월, <진달래꽃> (1925)',
    },
    {
      id: 'cp5_5',
      moduleId: 'mastery',
      target: '가시는 걸음 걸음 놓인 그 꽃을 사뿐히 즈려밟고 가시옵소서',
      translation: 'Step lightly and gently upon those flowers along your steps',
      attribution: '김소월, <진달래꽃> (1925)',
    },
    {
      id: 'cp5_6',
      moduleId: 'mastery',
      target: '넓은 벌 동쪽 끝으로 옛이야기 지줄대는 실개천이 휘돌아 나가고',
      translation: 'At the edge of wide plains, a babbling brook winds round with old tales',
      attribution: '정지용, <향수> (1927)',
    },
    {
      id: 'cp5_7',
      moduleId: 'mastery',
      target: '지금은 남의 땅, 빼앗긴 들에도 봄은 오는가',
      translation: 'Now someone else’s land, does spring come even to stolen fields?',
      attribution: '이상화, <빼앗긴 들에도 봄은 오는가> (1926)',
    },
    {
      id: 'cp5_8',
      moduleId: 'mastery',
      target: '날카로운 첫 키스의 추억은 나의 운명의 지침을 돌려놓고 사라졌습니다',
      translation: 'The memory of the sharp first kiss turned my destiny’s compass and vanished',
      attribution: '한용운, <님의 침묵> (1926)',
    },
    {
      id: 'cp5_9',
      moduleId: 'mastery',
      target: '강나루 건너서 밀밭 길을 구름에 달 가듯이 가는 나그네',
      translation:
        'Crossing the river ferry, walking through wheat fields like the moon through clouds',
      attribution: '박목월, <나그네> (1946)',
    },
    {
      id: 'cp5_10',
      moduleId: 'mastery',
      target: '다시 천고의 뒤에 백마 타고 오는 초인이 있어 이 광야에서 목놓아 부르게 하리라',
      translation: 'Let a superman on a white horse come to cry aloud in this wilderness',
      attribution: '이육사, <광야> (1944)',
    },
    {
      id: 'cp5_11',
      moduleId: 'mastery',
      target: '많은 책을 읽으며 지식을 넓혀요',
      translation: 'Expand knowledge by reading many books',
    },
    {
      id: 'cp5_12',
      moduleId: 'mastery',
      target: '의자에 편안하게 앉아서 쉬어요',
      translation: 'Sit comfortably in the chair and rest',
    },
    {
      id: 'cp5_13',
      moduleId: 'mastery',
      target: '닭고기로 끓인 따뜻한 삼계탕',
      translation: 'Warm ginseng chicken soup cooked with chicken',
    },
    {
      id: 'cp5_14',
      moduleId: 'mastery',
      target: '맑은 가을 하늘 아래 넓은 들판',
      translation: 'Wide open field under a clear autumn sky',
    },
    {
      id: 'cp5_15',
      moduleId: 'mastery',
      target: '젊은 날의 소중한 꿈과 삶',
      translation: 'Precious dreams and life of youth',
    },
    {
      id: 'cp5_16',
      moduleId: 'mastery',
      target: '어려움이 있어도 희망을 잃지 않아요',
      translation: 'Never lose hope even through hardship',
    },
    {
      id: 'cp5_17',
      moduleId: 'mastery',
      target: '값진 경험이 인생의 큰 자산이 됩니다',
      translation: 'Valuable experiences become great assets in life',
    },
    {
      id: 'cp5_18',
      moduleId: 'mastery',
      target: '자신의 몫을 다하는 성실한 태도',
      translation: 'A sincere attitude of fulfilling one’s own share',
    },
    {
      id: 'cp5_19',
      moduleId: 'mastery',
      target: '외곬으로 한 우물을 파는 장인정신',
      translation: 'Craftsmanship of digging a single well with single-minded devotion',
    },
    {
      id: 'cp5_20',
      moduleId: 'mastery',
      target: '밤하늘의 별을 보며 시를 읊어요',
      translation: 'Recite poetry while gazing at the night stars',
    },
    {
      id: 'cp5_21',
      moduleId: 'mastery',
      target: '흙 냄새 가득한 고향의 시골길',
      translation: 'A hometown country road filled with the scent of soil',
    },
    {
      id: 'cp5_22',
      moduleId: 'mastery',
      target: '서로를 닮아가는 정다운 사람들의 모습',
      translation: 'Affectionate people growing to resemble one another',
    },
    {
      id: 'cp5_23',
      moduleId: 'mastery',
      target: '마음이 넓고 너그러운 태도를 가져요',
      translation: 'Have an open-minded and generous attitude',
    },
    {
      id: 'cp5_24',
      moduleId: 'mastery',
      target: '많은 경험을 쌓아서 값진 지혜를 얻어요',
      translation: 'Gain valuable wisdom by accumulating many experiences',
    },
    {
      id: 'cp5_25',
      moduleId: 'mastery',
      target: '옳은 선택을 하기 위해 깊이 생각해요',
      translation: 'Think deeply to make the right choice',
    },
    {
      id: 'cp5_26',
      moduleId: 'mastery',
      target: '축하합니다! 모든 한글 자모를 마스터하셨습니다.',
      translation: 'Congratulations! You have mastered all Korean Hangul Jamos.',
    },
  ],
};

/**
 * Curated per-Batchim (final consonant) word and sentence banks for post-game Consolidation practice.
 * Every entry under a key strictly contains that batchim in at least one syllable.
 */
export const FOCUS_BATCHIM_VOCABULARY: Record<string, LessonItem[]> = {
  'ㄱ': [
    { id: 'fb_g_1', moduleId: 'mastery', target: '책', translation: 'Book' },
    { id: 'fb_g_2', moduleId: 'mastery', target: '학교', translation: 'School' },
    { id: 'fb_g_3', moduleId: 'mastery', target: '약속', translation: 'Promise / Appointment' },
    { id: 'fb_g_4', moduleId: 'mastery', target: '음악', translation: 'Music' },
    { id: 'fb_g_5', moduleId: 'mastery', target: '가족', translation: 'Family' },
    { id: 'fb_g_6', moduleId: 'mastery', target: '한국', translation: 'Korea' },
    { id: 'fb_g_7', moduleId: 'mastery', target: '역사', translation: 'History' },
    { id: 'fb_g_8', moduleId: 'mastery', target: '직접', translation: 'Directly / In person' },
    { id: 'fb_g_9', moduleId: 'mastery', target: '도서관에서 책을 빌려 읽어요', translation: 'Borrow and read books at the library' },
    { id: 'fb_g_10', moduleId: 'mastery', target: '친구와 소중한 약속을 지켜요', translation: 'Keep a precious promise with a friend' },
    { id: 'fb_g_11', moduleId: 'mastery', target: '아침에 따뜻한 국을 끓여요', translation: 'Cook warm soup in the morning' },
    { id: 'fb_g_12', moduleId: 'mastery', target: '가을 단풍이 붉게 물들어 갑니다', translation: 'Autumn leaves are turning red' },
  ],
  'ㄲ': [
    { id: 'fb_gg_1', moduleId: 'mastery', target: '밖', translation: 'Outside' },
    { id: 'fb_gg_2', moduleId: 'mastery', target: '깎다', translation: 'To peel / To cut down' },
    { id: 'fb_gg_3', moduleId: 'mastery', target: '꺾다', translation: 'To break / To snap' },
    { id: 'fb_gg_4', moduleId: 'mastery', target: '묶다', translation: 'To tie / To bind' },
    { id: 'fb_gg_5', moduleId: 'mastery', target: '닦다', translation: 'To wipe / To polish' },
    { id: 'fb_gg_6', moduleId: 'mastery', target: '섞다', translation: 'To mix / To blend' },
    { id: 'fb_gg_7', moduleId: 'mastery', target: '낚시', translation: 'Fishing' },
    { id: 'fb_gg_8', moduleId: 'mastery', target: '볶음밥', translation: 'Fried rice' },
    { id: 'fb_gg_9', moduleId: 'mastery', target: '사과 껍질을 예쁘게 깎아요', translation: 'Peel the apple skin nicely' },
    { id: 'fb_gg_10', moduleId: 'mastery', target: '창문을 깨끗하게 닦아요', translation: 'Wipe the window clean' },
    { id: 'fb_gg_11', moduleId: 'mastery', target: '밖에서 시원한 바람이 불어와요', translation: 'A cool breeze blows from outside' },
    { id: 'fb_gg_12', moduleId: 'mastery', target: '꺾이지 않는 마음으로 도전해요', translation: 'Take on challenges with an unbroken spirit' },
  ],
  'ㄳ': [
    { id: 'fb_gs_1', moduleId: 'mastery', target: '몫', translation: 'Share / Portion' },
    { id: 'fb_gs_2', moduleId: 'mastery', target: '넋', translation: 'Soul / Spirit' },
    { id: 'fb_gs_3', moduleId: 'mastery', target: '삯', translation: 'Wages / Fee' },
    { id: 'fb_gs_4', moduleId: 'mastery', target: '품삯', translation: 'Labor wage / Daily pay' },
    { id: 'fb_gs_5', moduleId: 'mastery', target: '뱃삯', translation: 'Boat fare' },
    { id: 'fb_gs_6', moduleId: 'mastery', target: '자신의 몫을 다하는 책임감', translation: 'Sense of responsibility in fulfilling one’s own share' },
    { id: 'fb_gs_7', moduleId: 'mastery', target: '넋을 잃고 아름다운 풍경을 바라봐요', translation: 'Gaze spellbound at the beautiful scenery' },
  ],
  'ㄴ': [
    { id: 'fb_n_1', moduleId: 'mastery', target: '눈', translation: 'Eye / Snow' },
    { id: 'fb_n_2', moduleId: 'mastery', target: '산', translation: 'Mountain' },
    { id: 'fb_n_3', moduleId: 'mastery', target: '손', translation: 'Hand' },
    { id: 'fb_n_4', moduleId: 'mastery', target: '친구', translation: 'Friend' },
    { id: 'fb_n_5', moduleId: 'mastery', target: '따뜻한 봄바람이 불어옵니다', translation: 'A warm spring breeze blows' },
    { id: 'fb_n_6', moduleId: 'mastery', target: '손을 잡고 함께 걸어가요', translation: 'Hold hands and walk together' },
  ],
  'ㄵ': [
    { id: 'fb_nj_1', moduleId: 'mastery', target: '앉다', translation: 'To sit' },
    { id: 'fb_nj_2', moduleId: 'mastery', target: '얹다', translation: 'To place on top' },
    { id: 'fb_nj_3', moduleId: 'mastery', target: '걸터앉다', translation: 'To sit on the edge' },
    { id: 'fb_nj_4', moduleId: 'mastery', target: '의자에 편안히 앉아서 쉬어요', translation: 'Sit comfortably in the chair and rest' },
    { id: 'fb_nj_5', moduleId: 'mastery', target: '밥 위에 계란을 살포시 얹어요', translation: 'Gently place an egg on top of the rice' },
  ],
  'ㄶ': [
    { id: 'fb_nh_1', moduleId: 'mastery', target: '많다', translation: 'To be many / much' },
    { id: 'fb_nh_2', moduleId: 'mastery', target: '않다', translation: 'To not do / To not be' },
    { id: 'fb_nh_3', moduleId: 'mastery', target: '괜찮다', translation: 'To be okay / To be fine' },
    { id: 'fb_nh_4', moduleId: 'mastery', target: '끊다', translation: 'To cut / To sever' },
    { id: 'fb_nh_5', moduleId: 'mastery', target: '많은 사람들과 정을 나누어요', translation: 'Share warmth with many people' },
    { id: 'fb_nh_6', moduleId: 'mastery', target: '포기하지 않고 끝까지 노력해요', translation: 'Endeavor to the end without giving up' },
  ],
  'ㄷ': [
    { id: 'fb_d_1', moduleId: 'mastery', target: '닫다', translation: 'To close' },
    { id: 'fb_d_2', moduleId: 'mastery', target: '곧', translation: 'Soon / Immediately' },
    { id: 'fb_d_3', moduleId: 'mastery', target: '믿음', translation: 'Faith / Trust' },
    { id: 'fb_d_4', moduleId: 'mastery', target: '돋보기', translation: 'Magnifying glass' },
    { id: 'fb_d_5', moduleId: 'mastery', target: '묻다', translation: 'To ask / To bury' },
    { id: 'fb_d_6', moduleId: 'mastery', target: '걷다', translation: 'To walk' },
    { id: 'fb_d_7', moduleId: 'mastery', target: '돋아나다', translation: 'To sprout / To spring up' },
    { id: 'fb_d_8', moduleId: 'mastery', target: '낟알', translation: 'Grain / Single grain' },
    { id: 'fb_d_9', moduleId: 'mastery', target: '창문을 꼭 닫고 바람을 막아요', translation: 'Close the window tightly to block the wind' },
    { id: 'fb_d_10', moduleId: 'mastery', target: '서로에 대한 굳은 믿음을 가져요', translation: 'Have steadfast trust in one another' },
    { id: 'fb_d_11', moduleId: 'mastery', target: '곧 좋은 소식이 들려올 거예요', translation: 'Good news will arrive soon' },
  ],
  'ㄹ': [
    { id: 'fb_r_1', moduleId: 'mastery', target: '물', translation: 'Water' },
    { id: 'fb_r_2', moduleId: 'mastery', target: '달', translation: 'Moon / Month' },
    { id: 'fb_r_3', moduleId: 'mastery', target: '길', translation: 'Road / Way' },
    { id: 'fb_r_4', moduleId: 'mastery', target: '하늘', translation: 'Sky' },
    { id: 'fb_r_5', moduleId: 'mastery', target: '맑은 하늘에 하얀 구름이 떠 있어요', translation: 'White clouds float in the clear sky' },
    { id: 'fb_r_6', moduleId: 'mastery', target: '시원한 물 한 잔을 마셔요', translation: 'Drink a glass of cool water' },
  ],
  'ㄺ': [
    { id: 'fb_rg_1', moduleId: 'mastery', target: '닭', translation: 'Chicken' },
    { id: 'fb_rg_2', moduleId: 'mastery', target: '흙', translation: 'Soil / Earth' },
    { id: 'fb_rg_3', moduleId: 'mastery', target: '읽다', translation: 'To read' },
    { id: 'fb_rg_4', moduleId: 'mastery', target: '맑다', translation: 'To be clear / clean' },
    { id: 'fb_rg_5', moduleId: 'mastery', target: '밝다', translation: 'To be bright' },
    { id: 'fb_rg_6', moduleId: 'mastery', target: '굵다', translation: 'To be thick' },
    { id: 'fb_rg_7', moduleId: 'mastery', target: '맑고 푸른 하늘 아래 흙 냄새', translation: 'Scent of earth under a clear blue sky' },
    { id: 'fb_rg_8', moduleId: 'mastery', target: '매일 아침 책을 소리 내어 읽어요', translation: 'Read books aloud every morning' },
  ],
  'ㄻ': [
    { id: 'fb_rm_1', moduleId: 'mastery', target: '삶', translation: 'Life' },
    { id: 'fb_rm_2', moduleId: 'mastery', target: '젊다', translation: 'To be young' },
    { id: 'fb_rm_3', moduleId: 'mastery', target: '닮다', translation: 'To resemble' },
    { id: 'fb_rm_4', moduleId: 'mastery', target: '굶다', translation: 'To starve / To skip a meal' },
    { id: 'fb_rm_5', moduleId: 'mastery', target: '삶의 소중한 가치를 깨달아요', translation: 'Realize the precious value of life' },
    { id: 'fb_rm_6', moduleId: 'mastery', target: '부모님을 꼭 닮은 다정한 미소', translation: 'A gentle smile closely resembling one’s parents' },
  ],
  'ㄼ': [
    { id: 'fb_rb_1', moduleId: 'mastery', target: '넓다', translation: 'To be wide / To be spacious' },
    { id: 'fb_rb_2', moduleId: 'mastery', target: '여덟', translation: 'Eight' },
    { id: 'fb_rb_3', moduleId: 'mastery', target: '밟다', translation: 'To step on' },
    { id: 'fb_rb_4', moduleId: 'mastery', target: '얇다', translation: 'To be thin' },
    { id: 'fb_rb_5', moduleId: 'mastery', target: '넓은 들판을 가로질러 달려가요', translation: 'Run across the wide open field' },
    { id: 'fb_rb_6', moduleId: 'mastery', target: '낙엽을 사뿐히 밟으며 산책해요', translation: 'Stroll stepping lightly on fallen leaves' },
  ],
  'ㄽ': [
    { id: 'fb_rs_1', moduleId: 'mastery', target: '외곬', translation: 'Single-minded path / Dedicated channel' },
    { id: 'fb_rs_2', moduleId: 'mastery', target: '넋두리', translation: 'Grumbling complaint / Lamentation' },
    { id: 'fb_rs_3', moduleId: 'mastery', target: '곬', translation: 'Channel / Waterway' },
    { id: 'fb_rs_4', moduleId: 'mastery', target: '외곬으로 한길을 걷는 장인', translation: 'A craftsman walking a single dedicated path' },
    { id: 'fb_rs_5', moduleId: 'mastery', target: '마음의 곬을 바로잡고 집중해요', translation: 'Straighten the course of one’s mind and focus' },
  ],
  'ㄾ': [
    { id: 'fb_rt_1', moduleId: 'mastery', target: '핥다', translation: 'To lick' },
    { id: 'fb_rt_2', moduleId: 'mastery', target: '훑다', translation: 'To skim / To browse through' },
    { id: 'fb_rt_3', moduleId: 'mastery', target: '책의 내용을 빠르게 훑어보아요', translation: 'Quickly skim through the contents of the book' },
    { id: 'fb_rt_4', moduleId: 'mastery', target: '강아지가 손을 정답게 핥아요', translation: 'The puppy affectionately licks my hand' },
  ],
  'ㄿ': [
    { id: 'fb_rp_1', moduleId: 'mastery', target: '읊다', translation: 'To recite / To chant' },
    { id: 'fb_rp_2', moduleId: 'mastery', target: '시를 읊다', translation: 'To recite poetry' },
    { id: 'fb_rp_3', moduleId: 'mastery', target: '달빛 아래서 고운 시를 읊어요', translation: 'Recite a lovely poem beneath the moonlight' },
    { id: 'fb_rp_4', moduleId: 'mastery', target: '옛 선비처럼 시조를 읊조려요', translation: 'Softly chant classical poetry like a scholar of old' },
  ],
  'ㅀ': [
    { id: 'fb_rh_1', moduleId: 'mastery', target: '잃다', translation: 'To lose' },
    { id: 'fb_rh_2', moduleId: 'mastery', target: '옳다', translation: 'To be right / correct' },
    { id: 'fb_rh_3', moduleId: 'mastery', target: '싫다', translation: 'To dislike / To hate' },
    { id: 'fb_rh_4', moduleId: 'mastery', target: '닳다', translation: 'To wear out / To wear down' },
    { id: 'fb_rh_5', moduleId: 'mastery', target: '어려움 속에서도 용기를 잃지 않아요', translation: 'Never lose courage even in times of trouble' },
    { id: 'fb_rh_6', moduleId: 'mastery', target: '옳은 일을 위해 바르게 행동해요', translation: 'Act uprightly for what is right' },
  ],
  'ㅁ': [
    { id: 'fb_m_1', moduleId: 'mastery', target: '봄', translation: 'Spring' },
    { id: 'fb_m_2', moduleId: 'mastery', target: '마음', translation: 'Mind / Heart' },
    { id: 'fb_m_3', moduleId: 'mastery', target: '바람', translation: 'Wind / Wish' },
    { id: 'fb_m_4', moduleId: 'mastery', target: '구름', translation: 'Cloud' },
    { id: 'fb_m_5', moduleId: 'mastery', target: '따스한 봄날의 햇살이 포근해요', translation: 'The sunshine of a warm spring day is cozy' },
    { id: 'fb_m_6', moduleId: 'mastery', target: '감사하는 마음으로 하루를 시작해요', translation: 'Begin the day with a grateful heart' },
  ],
  'ㅂ': [
    { id: 'fb_b_1', moduleId: 'mastery', target: '집', translation: 'House / Home' },
    { id: 'fb_b_2', moduleId: 'mastery', target: '밥', translation: 'Rice / Meal' },
    { id: 'fb_b_3', moduleId: 'mastery', target: '입', translation: 'Mouth / Lips' },
    { id: 'fb_b_4', moduleId: 'mastery', target: '수첩', translation: 'Notebook / Pocketbook' },
    { id: 'fb_b_5', moduleId: 'mastery', target: '가족과 함께 따뜻한 밥을 먹어요', translation: 'Eat a warm meal together with family' },
    { id: 'fb_b_6', moduleId: 'mastery', target: '포근하고 아늑한 우리 집', translation: 'Our warm and cozy home' },
  ],
  'ㅄ': [
    { id: 'fb_bs_1', moduleId: 'mastery', target: '값', translation: 'Price / Value' },
    { id: 'fb_bs_2', moduleId: 'mastery', target: '없다', translation: 'To not exist / lack' },
    { id: 'fb_bs_3', moduleId: 'mastery', target: '값지다', translation: 'To be valuable / To be priceless' },
    { id: 'fb_bs_4', moduleId: 'mastery', target: '값비싸다', translation: 'To be expensive / To be costly' },
    { id: 'fb_bs_5', moduleId: 'mastery', target: '값진 경험이 삶을 풍요롭게 해요', translation: 'Valuable experiences enrich one’s life' },
    { id: 'fb_bs_6', moduleId: 'mastery', target: '아무런 걱정 없이 편안하게 쉬어요', translation: 'Rest comfortably without any worries' },
  ],
  'ㅅ': [
    { id: 'fb_s_1', moduleId: 'mastery', target: '옷', translation: 'Clothes' },
    { id: 'fb_s_2', moduleId: 'mastery', target: '맛', translation: 'Taste / Flavor' },
    { id: 'fb_s_3', moduleId: 'mastery', target: '햇살', translation: 'Sunlight' },
    { id: 'fb_s_4', moduleId: 'mastery', target: '첫사랑', translation: 'First love' },
    { id: 'fb_s_5', moduleId: 'mastery', target: '옛날', translation: 'Old days / Past' },
    { id: 'fb_s_6', moduleId: 'mastery', target: '따스한 봄 햇살이 창가에 내려앉아요', translation: 'Warm spring sunlight rests upon the windowsill' },
    { id: 'fb_s_7', moduleId: 'mastery', target: '맛있는 음식을 나누며 즐겁게 웃어요', translation: 'Share delicious food and laugh happily' },
  ],
  'ㅆ': [
    { id: 'fb_ss_1', moduleId: 'mastery', target: '있다', translation: 'To exist / have' },
    { id: 'fb_ss_2', moduleId: 'mastery', target: '갔다', translation: 'Went' },
    { id: 'fb_ss_3', moduleId: 'mastery', target: '썼다', translation: 'Wrote / Used / Wore' },
    { id: 'fb_ss_4', moduleId: 'mastery', target: '봤다', translation: 'Saw' },
    { id: 'fb_ss_5', moduleId: 'mastery', target: '어제 친구에게 편지를 썼어요', translation: 'I wrote a letter to a friend yesterday' },
    { id: 'fb_ss_6', moduleId: 'mastery', target: '공원에 가서 푸른 나무를 보았어요', translation: 'I went to the park and saw green trees' },
  ],
  'ㅇ': [
    { id: 'fb_ng_1', moduleId: 'mastery', target: '강', translation: 'River' },
    { id: 'fb_ng_2', moduleId: 'mastery', target: '공', translation: 'Ball' },
    { id: 'fb_ng_3', moduleId: 'mastery', target: '사랑', translation: 'Love' },
    { id: 'fb_ng_4', moduleId: 'mastery', target: '희망', translation: 'Hope' },
    { id: 'fb_ng_5', moduleId: 'mastery', target: '푸른 강물이 유유히 흘러갑니다', translation: 'The blue river water flows leisurely' },
    { id: 'fb_ng_6', moduleId: 'mastery', target: '서로를 사랑하는 따뜻한 마음', translation: 'A warm heart loving one another' },
  ],
  'ㅈ': [
    { id: 'fb_j_1', moduleId: 'mastery', target: '낮', translation: 'Daytime' },
    { id: 'fb_j_2', moduleId: 'mastery', target: '늦다', translation: 'To be late' },
    { id: 'fb_j_3', moduleId: 'mastery', target: '잊다', translation: 'To forget' },
    { id: 'fb_j_4', moduleId: 'mastery', target: '맞다', translation: 'To be correct / fit' },
    { id: 'fb_j_5', moduleId: 'mastery', target: '젖다', translation: 'To get wet' },
    { id: 'fb_j_6', moduleId: 'mastery', target: '빚', translation: 'Debt' },
    { id: 'fb_j_7', moduleId: 'mastery', target: '꽂다', translation: 'To insert / To stick into' },
    { id: 'fb_j_8', moduleId: 'mastery', target: '늦잠을 자지 않고 일찍 일어나요', translation: 'Wake up early without oversleeping' },
    { id: 'fb_j_9', moduleId: 'mastery', target: '소중한 은혜를 영원히 잊지 않아요', translation: 'Never forget precious grace forever' },
    { id: 'fb_j_10', moduleId: 'mastery', target: '화병에 예쁜 꽃을 정성껏 꽂아요', translation: 'Carefully arrange pretty flowers in the vase' },
    { id: 'fb_j_11', moduleId: 'mastery', target: '비에 젖은 거리를 우산 쓰고 걸어요', translation: 'Walk the rain-soaked street holding an umbrella' },
  ],
  'ㅊ': [
    { id: 'fb_ch_1', moduleId: 'mastery', target: '꽃', translation: 'Flower' },
    { id: 'fb_ch_2', moduleId: 'mastery', target: '빛', translation: 'Light / Ray' },
    { id: 'fb_ch_3', moduleId: 'mastery', target: '낯', translation: 'Face / Countenance' },
    { id: 'fb_ch_4', moduleId: 'mastery', target: '숯', translation: 'Charcoal' },
    { id: 'fb_ch_5', moduleId: 'mastery', target: '돛', translation: 'Sail' },
    { id: 'fb_ch_6', moduleId: 'mastery', target: '쫓다', translation: 'To chase / To pursue' },
    { id: 'fb_ch_7', moduleId: 'mastery', target: '꽃밭', translation: 'Flower bed' },
    { id: 'fb_ch_8', moduleId: 'mastery', target: '빛나다', translation: 'To shine brightly' },
    { id: 'fb_ch_9', moduleId: 'mastery', target: '돛단배', translation: 'Sailboat' },
    { id: 'fb_ch_10', moduleId: 'mastery', target: '봄바람에 화사하게 피어난 꽃들', translation: 'Flowers blossoming brightly in the spring breeze' },
    { id: 'fb_ch_11', moduleId: 'mastery', target: '어둠 속에서 환하게 빛나는 등대', translation: 'A lighthouse shining brightly through darkness' },
    { id: 'fb_ch_12', moduleId: 'mastery', target: '바다 위를 미끄러지는 하얀 돛단배', translation: 'A white sailboat gliding over the sea' },
  ],
  'ㅋ': [
    { id: 'fb_k_1', moduleId: 'mastery', target: '부엌', translation: 'Kitchen' },
    { id: 'fb_k_2', moduleId: 'mastery', target: '동녘', translation: 'Eastern sky / East' },
    { id: 'fb_k_3', moduleId: 'mastery', target: '서녘', translation: 'Western sky / West' },
    { id: 'fb_k_4', moduleId: 'mastery', target: '남녘', translation: 'Southern sky / South' },
    { id: 'fb_k_5', moduleId: 'mastery', target: '북녘', translation: 'Northern sky / North' },
    { id: 'fb_k_6', moduleId: 'mastery', target: '들녘', translation: 'Field / Plain' },
    { id: 'fb_k_7', moduleId: 'mastery', target: '새벽녘', translation: 'Dawn / Daybreak' },
    { id: 'fb_k_8', moduleId: 'mastery', target: '해질녘', translation: 'Dusk / Sunset' },
    { id: 'fb_k_9', moduleId: 'mastery', target: '어스름녘', translation: 'Dusk / Twilight' },
    { id: 'fb_k_10', moduleId: 'mastery', target: '부엌문', translation: 'Kitchen door' },
    { id: 'fb_k_11', moduleId: 'mastery', target: '부엌일', translation: 'Kitchen chores' },
    { id: 'fb_k_12', moduleId: 'mastery', target: '부엌칼', translation: 'Kitchen knife' },
    { id: 'fb_k_13', moduleId: 'mastery', target: '어머니가 맛있는 음식을 만드는 부엌', translation: 'The kitchen where mother prepares delicious meals' },
    { id: 'fb_k_14', moduleId: 'mastery', target: '살포시 밝아오는 고요한 새벽녘', translation: 'The quiet dawn softly brightening up' },
    { id: 'fb_k_15', moduleId: 'mastery', target: '서녘 하늘에 붉은 노을이 아름답게 물들어요', translation: 'Red sunset colors dye the western sky beautifully' },
    { id: 'fb_k_16', moduleId: 'mastery', target: '황금빛 벼가 물결치는 가을 들녘', translation: 'Autumn fields undulating with golden rice' },
    { id: 'fb_k_17', moduleId: 'mastery', target: '해질녘 강변을 따라 천천히 걸어요', translation: 'Stroll slowly along the riverside at dusk' },
  ],
  'ㅌ': [
    { id: 'fb_t_1', moduleId: 'mastery', target: '밭', translation: 'Field / Farm' },
    { id: 'fb_t_2', moduleId: 'mastery', target: '끝', translation: 'End / Finish' },
    { id: 'fb_t_3', moduleId: 'mastery', target: '솥', translation: 'Pot / Cauldron' },
    { id: 'fb_t_4', moduleId: 'mastery', target: '밑', translation: 'Bottom / Below' },
    { id: 'fb_t_5', moduleId: 'mastery', target: '팥', translation: 'Red bean' },
    { id: 'fb_t_6', moduleId: 'mastery', target: '겉', translation: 'Surface / Outside' },
    { id: 'fb_t_7', moduleId: 'mastery', target: '곁', translation: 'Side / Beside' },
    { id: 'fb_t_8', moduleId: 'mastery', target: '붙다', translation: 'To stick / To pass (exam)' },
    { id: 'fb_t_9', moduleId: 'mastery', target: '뱉다', translation: 'To spit out' },
    { id: 'fb_t_10', moduleId: 'mastery', target: '짙다', translation: 'To be deep / To be thick' },
    { id: 'fb_t_11', moduleId: 'mastery', target: '맡다', translation: 'To take charge of / To smell' },
    { id: 'fb_t_12', moduleId: 'mastery', target: '끝까지 최선을 다해 달립니다', translation: 'Run giving my best effort until the end' },
    { id: 'fb_t_13', moduleId: 'mastery', target: '곁에서 힘이 되어 주는 든든한 친구', translation: 'A dependable friend who gives strength by my side' },
    { id: 'fb_t_14', moduleId: 'mastery', target: '밭에서 싱싱한 채소를 가꾸어요', translation: 'Cultivate fresh vegetables in the garden field' },
  ],
  'ㅍ': [
    { id: 'fb_p_1', moduleId: 'mastery', target: '앞', translation: 'Front / Ahead' },
    { id: 'fb_p_2', moduleId: 'mastery', target: '잎', translation: 'Leaf' },
    { id: 'fb_p_3', moduleId: 'mastery', target: '숲', translation: 'Forest / Woods' },
    { id: 'fb_p_4', moduleId: 'mastery', target: '늪', translation: 'Swamp / Marsh' },
    { id: 'fb_p_5', moduleId: 'mastery', target: '옆', translation: 'Next to / Side' },
    { id: 'fb_p_6', moduleId: 'mastery', target: '짚', translation: 'Straw' },
    { id: 'fb_p_7', moduleId: 'mastery', target: '덮다', translation: 'To cover' },
    { id: 'fb_p_8', moduleId: 'mastery', target: '깊다', translation: 'To be deep' },
    { id: 'fb_p_9', moduleId: 'mastery', target: '높다', translation: 'To be high / To be tall' },
    { id: 'fb_p_10', moduleId: 'mastery', target: '갚다', translation: 'To repay' },
    { id: 'fb_p_11', moduleId: 'mastery', target: '푸른 나뭇잎이 바람에 흔들려요', translation: 'Green tree leaves sway in the wind' },
    { id: 'fb_p_12', moduleId: 'mastery', target: '앞을 향해 자신감 있게 나아가요', translation: 'Step forward toward the future with confidence' },
    { id: 'fb_p_13', moduleId: 'mastery', target: '새소리 가득한 깊은 숲속 길', translation: 'A trail deep in the forest filled with birdsong' },
  ],
  'ㅎ': [
    { id: 'fb_h_1', moduleId: 'mastery', target: '좋다', translation: 'To be good / To be nice' },
    { id: 'fb_h_2', moduleId: 'mastery', target: '놓다', translation: 'To put / To place' },
    { id: 'fb_h_3', moduleId: 'mastery', target: '넣다', translation: 'To insert / To put inside' },
    { id: 'fb_h_4', moduleId: 'mastery', target: '닿다', translation: 'To reach / To touch' },
    { id: 'fb_h_5', moduleId: 'mastery', target: '쌓다', translation: 'To stack / To build up' },
    { id: 'fb_h_6', moduleId: 'mastery', target: '낳다', translation: 'To give birth / To produce' },
    { id: 'fb_h_7', moduleId: 'mastery', target: '땋다', translation: 'To braid' },
    { id: 'fb_h_8', moduleId: 'mastery', target: '마음씨가 참 곱고 좋습니다', translation: 'Having a truly kind and pleasant heart' },
    { id: 'fb_h_9', moduleId: 'mastery', target: '가방 안에 필기도구를 가지런히 넣어요', translation: 'Neatly put stationery inside the bag' },
    { id: 'fb_h_10', moduleId: 'mastery', target: '벽돌을 차곡차곡 쌓아 올려요', translation: 'Stack bricks one upon another steadily' },
    { id: 'fb_h_11', moduleId: 'mastery', target: '손이 닿는 곳에 책을 놓아두어요', translation: 'Keep the book within arm’s reach' },
  ],
};

