import type { LessonItem } from '../types/korean';

/**
 * Curated per-Jamo short word banks (1–3 words / length <= 12 characters).
 * Every entry for a given Jamo is strictly composed only of that Jamo and preceding unlocked Jamos.
 */
export const MASTERY_JAMO_VOCABULARY: Record<string, LessonItem[]> = {
  // --- Stage 1: Home Row Index Keys (ㅓ, ㅏ, ㅇ, ㄹ) ---
  'ㅓ': [
    { id: 'mv_eo_1', moduleId: 'mastery', target: '어', translation: 'Oh / Well' },
    { id: 'mv_eo_2', moduleId: 'mastery', target: '어어', translation: 'Uh-oh' },
    { id: 'mv_eo_3', moduleId: 'mastery', target: '어어어', translation: 'Expressing surprise' },
  ],
  'ㅏ': [
    { id: 'mv_a_1', moduleId: 'mastery', target: '아', translation: 'Ah' },
    { id: 'mv_a_2', moduleId: 'mastery', target: '아아', translation: 'Ah ah' },
    { id: 'mv_a_3', moduleId: 'mastery', target: '아아아', translation: 'Ahhh' },
    { id: 'mv_a_4', moduleId: 'mastery', target: '아라', translation: 'Ara (ancient sea)' },
  ],
  'ㅇ': [
    { id: 'mv_ng_1', moduleId: 'mastery', target: '앙', translation: 'Bite / Ang' },
    { id: 'mv_ng_2', moduleId: 'mastery', target: '엉', translation: 'Ung' },
    { id: 'mv_ng_3', moduleId: 'mastery', target: '앙앙', translation: 'Crying sound' },
    { id: 'mv_ng_4', moduleId: 'mastery', target: '엉엉', translation: 'Sobbing sound' },
  ],
  'ㄹ': [
    { id: 'mv_r_1', moduleId: 'mastery', target: '알', translation: 'Egg / Grain' },
    { id: 'mv_r_2', moduleId: 'mastery', target: '얼', translation: 'Spirit / Soul' },
    { id: 'mv_r_3', moduleId: 'mastery', target: '라', translation: 'Ra / La' },
    { id: 'mv_r_4', moduleId: 'mastery', target: '러', translation: 'Reo' },
    { id: 'mv_r_5', moduleId: 'mastery', target: '알아', translation: 'I know' },
    { id: 'mv_r_6', moduleId: 'mastery', target: '어라', translation: 'Huh? / Oh dear' },
    { id: 'mv_r_7', moduleId: 'mastery', target: '아라', translation: 'Ara (Ancient Sea)' },
    { id: 'mv_r_8', moduleId: 'mastery', target: '얼라', translation: 'Child (dialect)' },
  ],

  // --- Stage 2: Remaining Home Row & Basic Vowels (ㅗ, ㅣ, ㅁ, ㄴ, ㅎ, ㅜ, ㅡ) ---
  'ㅗ': [
    { id: 'mv_o_1', moduleId: 'mastery', target: '오', translation: 'Five / Oh' },
    { id: 'mv_o_2', moduleId: 'mastery', target: '올', translation: 'Strand / Warp' },
    { id: 'mv_o_3', moduleId: 'mastery', target: '로', translation: 'Path / Furnace' },
    { id: 'mv_o_4', moduleId: 'mastery', target: '오라', translation: 'Come (imperative)' },
    { id: 'mv_o_5', moduleId: 'mastery', target: '올라', translation: 'Go up' },
    { id: 'mv_o_6', moduleId: 'mastery', target: '오로라', translation: 'Aurora' },
    { id: 'mv_o_7', moduleId: 'mastery', target: '오알', translation: 'O-R' },
  ],
  'ㅣ': [
    { id: 'mv_i_1', moduleId: 'mastery', target: '이', translation: 'Tooth / Two / This' },
    { id: 'mv_i_2', moduleId: 'mastery', target: '일', translation: 'One / Day / Work' },
    { id: 'mv_i_3', moduleId: 'mastery', target: '아이', translation: 'Child' },
    { id: 'mv_i_4', moduleId: 'mastery', target: '오이', translation: 'Cucumber' },
    { id: 'mv_i_5', moduleId: 'mastery', target: '이리', translation: 'Wolf / This way' },
    { id: 'mv_i_6', moduleId: 'mastery', target: '일이', translation: 'Work / Task' },
    { id: 'mv_i_7', moduleId: 'mastery', target: '릴리', translation: 'Lily' },
  ],
  'ㅁ': [
    { id: 'mv_m_1', moduleId: 'mastery', target: '말', translation: 'Horse / Words' },
    { id: 'mv_m_2', moduleId: 'mastery', target: '몸', translation: 'Body' },
    { id: 'mv_m_3', moduleId: 'mastery', target: '엄마', translation: 'Mom' },
    { id: 'mv_m_4', moduleId: 'mastery', target: '이마', translation: 'Forehead' },
    { id: 'mv_m_5', moduleId: 'mastery', target: '마리', translation: 'Counter for animals' },
    { id: 'mv_m_6', moduleId: 'mastery', target: '모아', translation: 'Gather' },
    { id: 'mv_m_7', moduleId: 'mastery', target: '모이', translation: 'Bird feed' },
    { id: 'mv_m_8', moduleId: 'mastery', target: '미라', translation: 'Mummy' },
    { id: 'mv_m_9', moduleId: 'mastery', target: '모말', translation: 'Horsehair' },
  ],
  'ㄴ': [
    { id: 'mv_n_1', moduleId: 'mastery', target: '나', translation: 'I / Me' },
    { id: 'mv_n_2', moduleId: 'mastery', target: '너', translation: 'You' },
    { id: 'mv_n_3', moduleId: 'mastery', target: '나라', translation: 'Country / Nation' },
    { id: 'mv_n_4', moduleId: 'mastery', target: '나이', translation: 'Age' },
    { id: 'mv_n_5', moduleId: 'mastery', target: '날', translation: 'Day / Blade' },
    { id: 'mv_n_6', moduleId: 'mastery', target: '언니', translation: 'Older sister (for female)' },
    { id: 'mv_n_7', moduleId: 'mastery', target: '어머니', translation: 'Mother' },
    { id: 'mv_n_8', moduleId: 'mastery', target: '미나리', translation: 'Water dropwort' },
    { id: 'mv_n_9', moduleId: 'mastery', target: '안', translation: 'Inside / Not' },
    { id: 'mv_n_10', moduleId: 'mastery', target: '인', translation: 'Person / Seal' },
    { id: 'mv_n_11', moduleId: 'mastery', target: '온', translation: 'All / Whole' },
    { id: 'mv_n_12', moduleId: 'mastery', target: '놀이', translation: 'Play / Game' },
  ],
  'ㅎ': [
    { id: 'mv_h_1', moduleId: 'mastery', target: '하나', translation: 'One' },
    { id: 'mv_h_2', moduleId: 'mastery', target: '한', translation: 'One / Korean' },
    { id: 'mv_h_3', moduleId: 'mastery', target: '혼', translation: 'Soul / Spirit' },
    { id: 'mv_h_4', moduleId: 'mastery', target: '힘', translation: 'Strength / Power' },
    { id: 'mv_h_5', moduleId: 'mastery', target: '허리', translation: 'Waist / Lower back' },
    { id: 'mv_h_6', moduleId: 'mastery', target: '하이', translation: 'Hi' },
    { id: 'mv_h_7', moduleId: 'mastery', target: '호호', translation: 'Ho-ho (laughter)' },
    { id: 'mv_h_8', moduleId: 'mastery', target: '할머니', translation: 'Grandmother' },
    { id: 'mv_h_9', moduleId: 'mastery', target: '하하', translation: 'Ha-ha' },
  ],
  'ㅜ': [
    { id: 'mv_u_1', moduleId: 'mastery', target: '우리', translation: 'We / Us / Cage' },
    { id: 'mv_u_2', moduleId: 'mastery', target: '물', translation: 'Water' },
    { id: 'mv_u_3', moduleId: 'mastery', target: '문', translation: 'Door / Gate' },
    { id: 'mv_u_4', moduleId: 'mastery', target: '나무', translation: 'Tree / Wood' },
    { id: 'mv_u_5', moduleId: 'mastery', target: '누나', translation: 'Older sister (for male)' },
    { id: 'mv_u_6', moduleId: 'mastery', target: '눈', translation: 'Eye / Snow' },
    { id: 'mv_u_7', moduleId: 'mastery', target: '하루', translation: 'One day' },
    { id: 'mv_u_8', moduleId: 'mastery', target: '눈물', translation: 'Tears' },
    { id: 'mv_u_9', moduleId: 'mastery', target: '우물', translation: 'Well (water source)' },
    { id: 'mv_u_10', moduleId: 'mastery', target: '후', translation: 'After / Later' },
    { id: 'mv_u_11', moduleId: 'mastery', target: '무', translation: 'Radish' },
    { id: 'mv_u_12', moduleId: 'mastery', target: '루머', translation: 'Rumor' },
    { id: 'mv_u_13', moduleId: 'mastery', target: '우루루', translation: 'In a rush' },
  ],
  'ㅡ': [
    { id: 'mv_eu_1', moduleId: 'mastery', target: '이름', translation: 'Name' },
    { id: 'mv_eu_2', moduleId: 'mastery', target: '마음', translation: 'Heart / Mind' },
    { id: 'mv_eu_3', moduleId: 'mastery', target: '하늘', translation: 'Sky' },
    { id: 'mv_eu_4', moduleId: 'mastery', target: '흐름', translation: 'Flow / Current' },
    { id: 'mv_eu_5', moduleId: 'mastery', target: '어른', translation: 'Adult / Elder' },
    { id: 'mv_eu_6', moduleId: 'mastery', target: '으음', translation: 'Hmm' },
    { id: 'mv_eu_7', moduleId: 'mastery', target: '느림', translation: 'Slowness' },
    { id: 'mv_eu_8', moduleId: 'mastery', target: '흐린 날', translation: 'Cloudy day' },
  ],

  // --- Stage 3: Top Row Keys (ㄱ, ㅅ, ㄷ, ㅈ, ㅂ, ㅛ, ㅕ, ㅑ, ㅐ, ㅔ) ---
  'ㄱ': [
    { id: 'mv_g_1', moduleId: 'mastery', target: '가구', translation: 'Furniture' },
    { id: 'mv_g_2', moduleId: 'mastery', target: '고기', translation: 'Meat' },
    { id: 'mv_g_3', moduleId: 'mastery', target: '가을', translation: 'Autumn' },
    { id: 'mv_g_4', moduleId: 'mastery', target: '길', translation: 'Road / Street' },
    { id: 'mv_g_5', moduleId: 'mastery', target: '구름', translation: 'Cloud' },
    { id: 'mv_g_6', moduleId: 'mastery', target: '강', translation: 'River' },
    { id: 'mv_g_7', moduleId: 'mastery', target: '감', translation: 'Persimmon / Feeling' },
    { id: 'mv_g_8', moduleId: 'mastery', target: '국', translation: 'Soup / Nation' },
    { id: 'mv_g_9', moduleId: 'mastery', target: '그림', translation: 'Picture / Drawing' },
  ],
  'ㅅ': [
    { id: 'mv_s_1', moduleId: 'mastery', target: '사람', translation: 'Person / Human' },
    { id: 'mv_s_2', moduleId: 'mastery', target: '사랑', translation: 'Love' },
    { id: 'mv_s_3', moduleId: 'mastery', target: '소', translation: 'Cow / Bull' },
    { id: 'mv_s_4', moduleId: 'mastery', target: '손', translation: 'Hand' },
    { id: 'mv_s_5', moduleId: 'mastery', target: '시간', translation: 'Time / Hour' },
    { id: 'mv_s_6', moduleId: 'mastery', target: '소리', translation: 'Sound / Noise' },
    { id: 'mv_s_7', moduleId: 'mastery', target: '산', translation: 'Mountain' },
    { id: 'mv_s_8', moduleId: 'mastery', target: '사슴', translation: 'Deer' },
    { id: 'mv_s_9', moduleId: 'mastery', target: '시소', translation: 'Seesaw' },
  ],
  'ㄷ': [
    { id: 'mv_d_1', moduleId: 'mastery', target: '다리', translation: 'Leg / Bridge' },
    { id: 'mv_d_2', moduleId: 'mastery', target: '달', translation: 'Moon / Month' },
    { id: 'mv_d_3', moduleId: 'mastery', target: '돈', translation: 'Money' },
    { id: 'mv_d_4', moduleId: 'mastery', target: '돌', translation: 'Stone / Rock' },
    { id: 'mv_d_5', moduleId: 'mastery', target: '들', translation: 'Field / Plural marker' },
    { id: 'mv_d_6', moduleId: 'mastery', target: '도마', translation: 'Cutting board' },
    { id: 'mv_d_7', moduleId: 'mastery', target: '도시', translation: 'City' },
    { id: 'mv_d_8', moduleId: 'mastery', target: '두 사람', translation: 'Two people' },
  ],
  'ㅈ': [
    { id: 'mv_j_1', moduleId: 'mastery', target: '지도', translation: 'Map' },
    { id: 'mv_j_2', moduleId: 'mastery', target: '자리', translation: 'Seat / Spot' },
    { id: 'mv_j_3', moduleId: 'mastery', target: '잠', translation: 'Sleep' },
    { id: 'mv_j_4', moduleId: 'mastery', target: '주말', translation: 'Weekend' },
    { id: 'mv_j_5', moduleId: 'mastery', target: '자석', translation: 'Magnet' },
    { id: 'mv_j_6', moduleId: 'mastery', target: '자라', translation: 'Softshell turtle / Grow' },
  ],
  'ㅂ': [
    { id: 'mv_b_1', moduleId: 'mastery', target: '바다', translation: 'Sea / Ocean' },
    { id: 'mv_b_2', moduleId: 'mastery', target: '밥', translation: 'Rice / Meal' },
    { id: 'mv_b_3', moduleId: 'mastery', target: '발', translation: 'Foot' },
    { id: 'mv_b_4', moduleId: 'mastery', target: '밤', translation: 'Night / Chestnut' },
    { id: 'mv_b_5', moduleId: 'mastery', target: '봄', translation: 'Spring season' },
    { id: 'mv_b_6', moduleId: 'mastery', target: '바람', translation: 'Wind / Breeze' },
    { id: 'mv_b_7', moduleId: 'mastery', target: '방', translation: 'Room' },
    { id: 'mv_b_8', moduleId: 'mastery', target: '비', translation: 'Rain' },
    { id: 'mv_b_9', moduleId: 'mastery', target: '집', translation: 'House / Home' },
    { id: 'mv_b_10', moduleId: 'mastery', target: '지갑', translation: 'Wallet' },
  ],
  'ㅛ': [
    { id: 'mv_yo_1', moduleId: 'mastery', target: '요리', translation: 'Cooking / Cuisine' },
    { id: 'mv_yo_2', moduleId: 'mastery', target: '교실', translation: 'Classroom' },
    { id: 'mv_yo_3', moduleId: 'mastery', target: '요일', translation: 'Day of week' },
    { id: 'mv_yo_4', moduleId: 'mastery', target: '요구', translation: 'Demand / Request' },
    { id: 'mv_yo_5', moduleId: 'mastery', target: '음료', translation: 'Beverage / Drink' },
    { id: 'mv_yo_6', moduleId: 'mastery', target: '요람', translation: 'Cradle' },
  ],
  'ㅕ': [
    { id: 'mv_yeo_1', moduleId: 'mastery', target: '여기', translation: 'Here' },
    { id: 'mv_yeo_2', moduleId: 'mastery', target: '여름', translation: 'Summer' },
    { id: 'mv_yeo_3', moduleId: 'mastery', target: '여자', translation: 'Woman / Female' },
    { id: 'mv_yeo_4', moduleId: 'mastery', target: '연습', translation: 'Practice' },
    { id: 'mv_yeo_5', moduleId: 'mastery', target: '역', translation: 'Station' },
    { id: 'mv_yeo_6', moduleId: 'mastery', target: '연기', translation: 'Smoke / Acting' },
  ],
  'ㅑ': [
    { id: 'mv_ya_1', moduleId: 'mastery', target: '이야기', translation: 'Story / Conversation' },
    { id: 'mv_ya_2', moduleId: 'mastery', target: '야구', translation: 'Baseball' },
    { id: 'mv_ya_3', moduleId: 'mastery', target: '양', translation: 'Sheep / Quantity' },
    { id: 'mv_ya_4', moduleId: 'mastery', target: '약속', translation: 'Promise / Appointment' },
    { id: 'mv_ya_5', moduleId: 'mastery', target: '야경', translation: 'Night view' },
  ],
  'ㅐ': [
    { id: 'mv_ae_1', moduleId: 'mastery', target: '노래', translation: 'Song' },
    { id: 'mv_ae_2', moduleId: 'mastery', target: '배', translation: 'Boat / Pear / Stomach' },
    { id: 'mv_ae_3', moduleId: 'mastery', target: '새', translation: 'Bird / New' },
    { id: 'mv_ae_4', moduleId: 'mastery', target: '해', translation: 'Sun / Year' },
    { id: 'mv_ae_5', moduleId: 'mastery', target: '개미', translation: 'Ant' },
    { id: 'mv_ae_6', moduleId: 'mastery', target: '매일', translation: 'Every day' },
    { id: 'mv_ae_7', moduleId: 'mastery', target: '여행', translation: 'Travel / Trip' },
    { id: 'mv_ae_8', moduleId: 'mastery', target: '열매', translation: 'Fruit / Berry' },
  ],
  'ㅔ': [
    { id: 'mv_e_1', moduleId: 'mastery', target: '가게', translation: 'Shop / Store' },
    { id: 'mv_e_2', moduleId: 'mastery', target: '베개', translation: 'Pillow' },
    { id: 'mv_e_3', moduleId: 'mastery', target: '세상', translation: 'World / Earth' },
    { id: 'mv_e_4', moduleId: 'mastery', target: '제비', translation: 'Swallow (bird)' },
    { id: 'mv_e_5', moduleId: 'mastery', target: '세금', translation: 'Tax' },
    { id: 'mv_e_6', moduleId: 'mastery', target: '메모', translation: 'Memo' },
  ],

  // --- Stage 4: Bottom Row Keys (ㅋ, ㅌ, ㅊ, ㅍ, ㅠ) ---
  'ㅋ': [
    { id: 'mv_k_1', moduleId: 'mastery', target: '코', translation: 'Nose' },
    { id: 'mv_k_2', moduleId: 'mastery', target: '카메라', translation: 'Camera' },
    { id: 'mv_k_3', moduleId: 'mastery', target: '쿠키', translation: 'Cookie' },
    { id: 'mv_k_4', moduleId: 'mastery', target: '카드', translation: 'Card' },
    { id: 'mv_k_5', moduleId: 'mastery', target: '키', translation: 'Height / Key' },
    { id: 'mv_k_6', moduleId: 'mastery', target: '콩', translation: 'Bean / Pea' },
    { id: 'mv_k_7', moduleId: 'mastery', target: '퀴즈', translation: 'Quiz' },
    { id: 'mv_k_8', moduleId: 'mastery', target: '코너', translation: 'Corner' },
  ],
  'ㅌ': [
    { id: 'mv_t_1', moduleId: 'mastery', target: '토마토', translation: 'Tomato' },
    { id: 'mv_t_2', moduleId: 'mastery', target: '타이어', translation: 'Tire' },
    { id: 'mv_t_3', moduleId: 'mastery', target: '탁자', translation: 'Table / Desk' },
    { id: 'mv_t_4', moduleId: 'mastery', target: '턱', translation: 'Chin / Jaw' },
    { id: 'mv_t_5', moduleId: 'mastery', target: '태양', translation: 'Sun / Solar' },
    { id: 'mv_t_6', moduleId: 'mastery', target: '택시', translation: 'Taxi' },
    { id: 'mv_t_7', moduleId: 'mastery', target: '코트', translation: 'Coat' },
    { id: 'mv_t_8', moduleId: 'mastery', target: '티켓', translation: 'Ticket' },
    { id: 'mv_t_9', moduleId: 'mastery', target: '탈', translation: 'Mask' },
  ],
  'ㅊ': [
    { id: 'mv_ch_1', moduleId: 'mastery', target: '친구', translation: 'Friend' },
    { id: 'mv_ch_2', moduleId: 'mastery', target: '차', translation: 'Car / Tea' },
    { id: 'mv_ch_3', moduleId: 'mastery', target: '책', translation: 'Book' },
    { id: 'mv_ch_4', moduleId: 'mastery', target: '창문', translation: 'Window' },
    { id: 'mv_ch_5', moduleId: 'mastery', target: '치마', translation: 'Skirt' },
    { id: 'mv_ch_6', moduleId: 'mastery', target: '추억', translation: 'Memory / Reminiscence' },
    { id: 'mv_ch_7', moduleId: 'mastery', target: '자동차', translation: 'Automobile / Car' },
    { id: 'mv_ch_8', moduleId: 'mastery', target: '축구', translation: 'Soccer' },
    { id: 'mv_ch_9', moduleId: 'mastery', target: '출발', translation: 'Departure' },
    { id: 'mv_ch_10', moduleId: 'mastery', target: '청춘', translation: 'Youth' },
    { id: 'mv_ch_11', moduleId: 'mastery', target: '치즈', translation: 'Cheese' },
    { id: 'mv_ch_12', moduleId: 'mastery', target: '춤', translation: 'Dance' },
  ],
  'ㅍ': [
    { id: 'mv_p_1', moduleId: 'mastery', target: '파도', translation: 'Wave / Surf' },
    { id: 'mv_p_2', moduleId: 'mastery', target: '우표', translation: 'Postage stamp' },
    { id: 'mv_p_3', moduleId: 'mastery', target: '포도', translation: 'Grape' },
    { id: 'mv_p_4', moduleId: 'mastery', target: '편지', translation: 'Letter' },
    { id: 'mv_p_5', moduleId: 'mastery', target: '피아노', translation: 'Piano' },
    { id: 'mv_p_6', moduleId: 'mastery', target: '피부', translation: 'Skin' },
    { id: 'mv_p_7', moduleId: 'mastery', target: '커피', translation: 'Coffee' },
    { id: 'mv_p_8', moduleId: 'mastery', target: '풀', translation: 'Grass' },
    { id: 'mv_p_9', moduleId: 'mastery', target: '폭포', translation: 'Waterfall' },
    { id: 'mv_p_10', moduleId: 'mastery', target: '프로', translation: 'Professional' },
    { id: 'mv_p_11', moduleId: 'mastery', target: '캠프', translation: 'Camp' },
    { id: 'mv_p_12', moduleId: 'mastery', target: '테이프', translation: 'Tape' },
  ],
  'ㅠ': [
    { id: 'mv_yu_1', moduleId: 'mastery', target: '휴지', translation: 'Tissue / Paper' },
    { id: 'mv_yu_2', moduleId: 'mastery', target: '유리', translation: 'Glass' },
    { id: 'mv_yu_3', moduleId: 'mastery', target: '유학', translation: 'Study abroad' },
    { id: 'mv_yu_4', moduleId: 'mastery', target: '뉴스', translation: 'News' },
    { id: 'mv_yu_5', moduleId: 'mastery', target: '휴일', translation: 'Holiday' },
    { id: 'mv_yu_6', moduleId: 'mastery', target: '우유', translation: 'Milk' },
    { id: 'mv_yu_7', moduleId: 'mastery', target: '유명', translation: 'Fame / Famous' },
    { id: 'mv_yu_8', moduleId: 'mastery', target: '유월', translation: 'June' },
    { id: 'mv_yu_9', moduleId: 'mastery', target: '유행', translation: 'Trend / Fashion' },
  ],

  // --- Stage 5: Shift Keys (ㄲ, ㅆ, ㄸ, ㅉ, ㅃ, ㅒ, ㅖ) ---
  'ㄲ': [
    { id: 'mv_kk_1', moduleId: 'mastery', target: '까치', translation: 'Magpie' },
    { id: 'mv_kk_2', moduleId: 'mastery', target: '꼬마', translation: 'Little child' },
    { id: 'mv_kk_3', moduleId: 'mastery', target: '꽃', translation: 'Flower' },
    { id: 'mv_kk_4', moduleId: 'mastery', target: '꿈', translation: 'Dream' },
    { id: 'mv_kk_5', moduleId: 'mastery', target: '까마귀', translation: 'Crow / Raven' },
    { id: 'mv_kk_6', moduleId: 'mastery', target: '꽃병', translation: 'Flower vase' },
    { id: 'mv_kk_7', moduleId: 'mastery', target: '꼭', translation: 'Surely / Exactly' },
    { id: 'mv_kk_8', moduleId: 'mastery', target: '깨', translation: 'Sesame' },
    { id: 'mv_kk_9', moduleId: 'mastery', target: '껍질', translation: 'Skin / Peel / Bark' },
    { id: 'mv_kk_10', moduleId: 'mastery', target: '꽃길', translation: 'Flower path' },
    { id: 'mv_kk_11', moduleId: 'mastery', target: '꼬리', translation: 'Tail' },
  ],
  'ㅆ': [
    { id: 'mv_ss_1', moduleId: 'mastery', target: '쌀', translation: 'Uncooked rice' },
    { id: 'mv_ss_2', moduleId: 'mastery', target: '싸움', translation: 'Fight / Battle' },
    { id: 'mv_ss_3', moduleId: 'mastery', target: '씨앗', translation: 'Seed' },
    { id: 'mv_ss_4', moduleId: 'mastery', target: '쓰기', translation: 'Writing' },
    { id: 'mv_ss_5', moduleId: 'mastery', target: '쑥', translation: 'Mugwort' },
    { id: 'mv_ss_6', moduleId: 'mastery', target: '씨', translation: 'Seed / Mr. / Ms.' },
    { id: 'mv_ss_7', moduleId: 'mastery', target: '쏘다', translation: 'To shoot' },
    { id: 'mv_ss_8', moduleId: 'mastery', target: '썰매', translation: 'Sled' },
    { id: 'mv_ss_9', moduleId: 'mastery', target: '쌍둥이', translation: 'Twins' },
    { id: 'mv_ss_10', moduleId: 'mastery', target: '씨름', translation: 'Korean wrestling' },
    { id: 'mv_ss_11', moduleId: 'mastery', target: '썰다', translation: 'To slice / chop' },
  ],
  'ㄸ': [
    { id: 'mv_tt_1', moduleId: 'mastery', target: '떡', translation: 'Rice cake' },
    { id: 'mv_tt_2', moduleId: 'mastery', target: '딸기', translation: 'Strawberry' },
    { id: 'mv_tt_3', moduleId: 'mastery', target: '땅', translation: 'Land / Ground' },
    { id: 'mv_tt_4', moduleId: 'mastery', target: '땀', translation: 'Sweat' },
    { id: 'mv_tt_5', moduleId: 'mastery', target: '또', translation: 'Again / Also' },
    { id: 'mv_tt_6', moduleId: 'mastery', target: '뚜껑', translation: 'Lid / Cap' },
    { id: 'mv_tt_7', moduleId: 'mastery', target: '뜻', translation: 'Meaning / Will' },
    { id: 'mv_tt_8', moduleId: 'mastery', target: '뛰다', translation: 'To run / jump' },
    { id: 'mv_tt_9', moduleId: 'mastery', target: '딸', translation: 'Daughter' },
    { id: 'mv_tt_10', moduleId: 'mastery', target: '또다시', translation: 'Once again' },
    { id: 'mv_tt_11', moduleId: 'mastery', target: '떨림', translation: 'Tremor / Vibration' },
  ],
  'ㅉ': [
    { id: 'mv_jj_1', moduleId: 'mastery', target: '찌개', translation: 'Stew' },
    { id: 'mv_jj_2', moduleId: 'mastery', target: '짝', translation: 'Pair / Partner' },
    { id: 'mv_jj_3', moduleId: 'mastery', target: '쪽', translation: 'Side / Page / Direction' },
    { id: 'mv_jj_4', moduleId: 'mastery', target: '진짜', translation: 'Really / Real' },
    { id: 'mv_jj_5', moduleId: 'mastery', target: '짜장면', translation: 'Black bean noodles' },
    { id: 'mv_jj_6', moduleId: 'mastery', target: '짜다', translation: 'To be salty / squeeze' },
    { id: 'mv_jj_7', moduleId: 'mastery', target: '찜', translation: 'Steamed dish' },
    { id: 'mv_jj_8', moduleId: 'mastery', target: '쪽지', translation: 'Note / Memo' },
    { id: 'mv_jj_9', moduleId: 'mastery', target: '찌다', translation: 'To steam / gain weight' },
    { id: 'mv_jj_10', moduleId: 'mastery', target: '짜릿하다', translation: 'To be thrilling' },
  ],
  'ㅃ': [
    { id: 'mv_bb_1', moduleId: 'mastery', target: '빵', translation: 'Bread' },
    { id: 'mv_bb_2', moduleId: 'mastery', target: '뼈', translation: 'Bone' },
    { id: 'mv_bb_3', moduleId: 'mastery', target: '뿌리', translation: 'Root' },
    { id: 'mv_bb_4', moduleId: 'mastery', target: '뽀뽀', translation: 'Peck / Kiss' },
    { id: 'mv_bb_5', moduleId: 'mastery', target: '빨래', translation: 'Laundry' },
    { id: 'mv_bb_6', moduleId: 'mastery', target: '빠르다', translation: 'To be fast' },
    { id: 'mv_bb_7', moduleId: 'mastery', target: '뺨', translation: 'Cheek' },
    { id: 'mv_bb_8', moduleId: 'mastery', target: '빨리', translation: 'Quickly' },
    { id: 'mv_bb_9', moduleId: 'mastery', target: '빼다', translation: 'To subtract / remove' },
    { id: 'mv_bb_10', moduleId: 'mastery', target: '뽐내다', translation: 'To show off / boast' },
  ],
  'ㅒ': [
    { id: 'mv_yae_1', moduleId: 'mastery', target: '얘기', translation: 'Story / Chat' },
    { id: 'mv_yae_2', moduleId: 'mastery', target: '얘들아', translation: 'Hey guys / Children' },
    { id: 'mv_yae_3', moduleId: 'mastery', target: '얘', translation: 'This child / Hey' },
    { id: 'mv_yae_4', moduleId: 'mastery', target: '얘는', translation: 'This one is' },
    { id: 'mv_yae_5', moduleId: 'mastery', target: '얘기하다', translation: 'To talk / chat' },
    { id: 'mv_yae_6', moduleId: 'mastery', target: '걔', translation: 'That child' },
    { id: 'mv_yae_7', moduleId: 'mastery', target: '걔는', translation: 'That child is' },
    { id: 'mv_yae_8', moduleId: 'mastery', target: '쟤', translation: 'That child over there' },
    { id: 'mv_yae_9', moduleId: 'mastery', target: '쟤는', translation: 'That one over there is' },
    { id: 'mv_yae_10', moduleId: 'mastery', target: '얘기책', translation: 'Storybook' },
    { id: 'mv_yae_11', moduleId: 'mastery', target: '재미난 얘기', translation: 'Fun story' },
    { id: 'mv_yae_12', moduleId: 'mastery', target: '우리 얘기', translation: 'Our story' },
  ],
  'ㅖ': [
    { id: 'mv_ye_1', moduleId: 'mastery', target: '예절', translation: 'Manners / Etiquette' },
    { id: 'mv_ye_2', moduleId: 'mastery', target: '시계', translation: 'Clock / Watch' },
    { id: 'mv_ye_3', moduleId: 'mastery', target: '세계', translation: 'World / Globe' },
    { id: 'mv_ye_4', moduleId: 'mastery', target: '예술', translation: 'Art' },
    { id: 'mv_ye_5', moduleId: 'mastery', target: '예약', translation: 'Reservation' },
    { id: 'mv_ye_6', moduleId: 'mastery', target: '예보', translation: 'Forecast' },
    { id: 'mv_ye_7', moduleId: 'mastery', target: '예쁘다', translation: 'To be pretty' },
    { id: 'mv_ye_8', moduleId: 'mastery', target: '예의', translation: 'Politeness / Courtesy' },
    { id: 'mv_ye_9', moduleId: 'mastery', target: '예배', translation: 'Worship / Service' },
    { id: 'mv_ye_10', moduleId: 'mastery', target: '옛날얘기', translation: 'Old folktale' },
    { id: 'mv_ye_11', moduleId: 'mastery', target: '예감', translation: 'Premonition / Hunch' },
  ],

  // --- Stage 6: Compound Final Consonants (겹받침) ---
  'ㄶ': [
    { id: 'mv_nh_1', moduleId: 'mastery', target: '많다', translation: 'To be many / much' },
    { id: 'mv_nh_2', moduleId: 'mastery', target: '많이', translation: 'A lot / Much' },
    { id: 'mv_nh_3', moduleId: 'mastery', target: '많음', translation: 'Abundance' },
    { id: 'mv_nh_4', moduleId: 'mastery', target: '않다', translation: 'To not do' },
    { id: 'mv_nh_5', moduleId: 'mastery', target: '않아요', translation: 'Do not' },
    { id: 'mv_nh_6', moduleId: 'mastery', target: '않음', translation: 'Negation' },
    { id: 'mv_nh_7', moduleId: 'mastery', target: '괜찮다', translation: 'To be okay' },
    { id: 'mv_nh_8', moduleId: 'mastery', target: '괜찮아요', translation: 'It is okay' },
    { id: 'mv_nh_9', moduleId: 'mastery', target: '귀찮다', translation: 'To be tiresome / bothersome' },
    { id: 'mv_nh_10', moduleId: 'mastery', target: '점잖다', translation: 'To be gentle / well-mannered' },
    { id: 'mv_nh_11', moduleId: 'mastery', target: '하찮다', translation: 'To be trivial' },
  ],
  'ㄵ': [
    { id: 'mv_nj_1', moduleId: 'mastery', target: '앉다', translation: 'To sit' },
    { id: 'mv_nj_2', moduleId: 'mastery', target: '앉아', translation: 'Sit down' },
    { id: 'mv_nj_3', moduleId: 'mastery', target: '앉아요', translation: 'Please sit' },
    { id: 'mv_nj_4', moduleId: 'mastery', target: '앉음', translation: 'Sitting' },
    { id: 'mv_nj_5', moduleId: 'mastery', target: '앉히다', translation: 'To seat someone' },
    { id: 'mv_nj_6', moduleId: 'mastery', target: '걸터앉다', translation: 'To perch / sit astride' },
    { id: 'mv_nj_7', moduleId: 'mastery', target: '얹다', translation: 'To place on top' },
    { id: 'mv_nj_8', moduleId: 'mastery', target: '얹어', translation: 'Place on top' },
    { id: 'mv_nj_9', moduleId: 'mastery', target: '얹어요', translation: 'Put on top' },
    { id: 'mv_nj_10', moduleId: 'mastery', target: '얹히다', translation: 'To be placed on top' },
  ],
  'ㄺ': [
    { id: 'mv_lg_1', moduleId: 'mastery', target: '읽다', translation: 'To read' },
    { id: 'mv_lg_2', moduleId: 'mastery', target: '읽어요', translation: 'Read' },
    { id: 'mv_lg_3', moduleId: 'mastery', target: '읽기', translation: 'Reading' },
    { id: 'mv_lg_4', moduleId: 'mastery', target: '읽음', translation: 'Read (noun)' },
    { id: 'mv_lg_5', moduleId: 'mastery', target: '닭', translation: 'Chicken' },
    { id: 'mv_lg_6', moduleId: 'mastery', target: '닭고기', translation: 'Chicken meat' },
    { id: 'mv_lg_7', moduleId: 'mastery', target: '통닭', translation: 'Whole roast chicken' },
    { id: 'mv_lg_8', moduleId: 'mastery', target: '맑다', translation: 'To be clear' },
    { id: 'mv_lg_9', moduleId: 'mastery', target: '맑은', translation: 'Clear / Pure' },
    { id: 'mv_lg_10', moduleId: 'mastery', target: '맑음', translation: 'Clear weather' },
    { id: 'mv_lg_11', moduleId: 'mastery', target: '흙', translation: 'Soil / Earth' },
    { id: 'mv_lg_12', moduleId: 'mastery', target: '흙길', translation: 'Dirt road' },
    { id: 'mv_lg_13', moduleId: 'mastery', target: '붉다', translation: 'To be red' },
    { id: 'mv_lg_14', moduleId: 'mastery', target: '붉은', translation: 'Red (adj)' },
    { id: 'mv_lg_15', moduleId: 'mastery', target: '밝다', translation: 'To be bright' },
    { id: 'mv_lg_16', moduleId: 'mastery', target: '밝은', translation: 'Bright (adj)' },
    { id: 'mv_lg_17', moduleId: 'mastery', target: '굵다', translation: 'To be thick' },
    { id: 'mv_lg_18', moduleId: 'mastery', target: '굵은', translation: 'Thick (adj)' },
    { id: 'mv_lg_19', moduleId: 'mastery', target: '긁다', translation: 'To scratch' },
    { id: 'mv_lg_20', moduleId: 'mastery', target: '늙다', translation: 'To grow old' },
  ],
  'ㄻ': [
    { id: 'mv_lm_1', moduleId: 'mastery', target: '삶', translation: 'Life' },
    { id: 'mv_lm_2', moduleId: 'mastery', target: '삶다', translation: 'To boil' },
    { id: 'mv_lm_3', moduleId: 'mastery', target: '젊다', translation: 'To be young' },
    { id: 'mv_lm_4', moduleId: 'mastery', target: '젊음', translation: 'Youth' },
    { id: 'mv_lm_5', moduleId: 'mastery', target: '젊은이', translation: 'Young person' },
    { id: 'mv_lm_6', moduleId: 'mastery', target: '굶다', translation: 'To starve' },
    { id: 'mv_lm_7', moduleId: 'mastery', target: '굶주림', translation: 'Starvation' },
    { id: 'mv_lm_8', moduleId: 'mastery', target: '닮다', translation: 'To resemble' },
    { id: 'mv_lm_9', moduleId: 'mastery', target: '닮음', translation: 'Resemblance' },
    { id: 'mv_lm_10', moduleId: 'mastery', target: '옮다', translation: 'To catch / be infected' },
    { id: 'mv_lm_11', moduleId: 'mastery', target: '옮기다', translation: 'To move / transfer' },
    { id: 'mv_lm_12', moduleId: 'mastery', target: '앎', translation: 'Knowledge' },
  ],
  'ㄼ': [
    { id: 'mv_lb_1', moduleId: 'mastery', target: '넓다', translation: 'To be spacious / wide' },
    { id: 'mv_lb_2', moduleId: 'mastery', target: '넓은', translation: 'Spacious / Broad' },
    { id: 'mv_lb_3', moduleId: 'mastery', target: '넓이', translation: 'Area / Width' },
    { id: 'mv_lb_4', moduleId: 'mastery', target: '넓히다', translation: 'To widen' },
    { id: 'mv_lb_5', moduleId: 'mastery', target: '여덟', translation: 'Eight' },
    { id: 'mv_lb_6', moduleId: 'mastery', target: '여덟째', translation: 'Eighth' },
    { id: 'mv_lb_7', moduleId: 'mastery', target: '밟다', translation: 'To step on' },
    { id: 'mv_lb_8', moduleId: 'mastery', target: '밟아요', translation: 'Step on' },
    { id: 'mv_lb_9', moduleId: 'mastery', target: '짧다', translation: 'To be short' },
    { id: 'mv_lb_10', moduleId: 'mastery', target: '짧은', translation: 'Short (adj)' },
    { id: 'mv_lb_11', moduleId: 'mastery', target: '얇다', translation: 'To be thin' },
    { id: 'mv_lb_12', moduleId: 'mastery', target: '얇은', translation: 'Thin (adj)' },
  ],
  'ㅄ': [
    { id: 'mv_bs_1', moduleId: 'mastery', target: '없다', translation: 'To not exist / lack' },
    { id: 'mv_bs_2', moduleId: 'mastery', target: '없어요', translation: 'There is none' },
    { id: 'mv_bs_3', moduleId: 'mastery', target: '없음', translation: 'Absence / None' },
    { id: 'mv_bs_4', moduleId: 'mastery', target: '값', translation: 'Price / Value' },
    { id: 'mv_bs_5', moduleId: 'mastery', target: '값싸다', translation: 'To be cheap' },
    { id: 'mv_bs_6', moduleId: 'mastery', target: '값비싸다', translation: 'To be expensive' },
    { id: 'mv_bs_7', moduleId: 'mastery', target: '값진', translation: 'Priceless / Valuable' },
    { id: 'mv_bs_8', moduleId: 'mastery', target: '헐값', translation: 'Dirt-cheap price' },
    { id: 'mv_bs_9', moduleId: 'mastery', target: '몸값', translation: 'Ransom / Value' },
    { id: 'mv_bs_10', moduleId: 'mastery', target: '가없다', translation: 'Boundless / Endless' },
  ],
  'ㅀ': [
    { id: 'mv_lh_1', moduleId: 'mastery', target: '잃다', translation: 'To lose' },
    { id: 'mv_lh_2', moduleId: 'mastery', target: '잃어버리다', translation: 'To lose / misplace' },
    { id: 'mv_lh_3', moduleId: 'mastery', target: '잃음', translation: 'Loss' },
    { id: 'mv_lh_4', moduleId: 'mastery', target: '싫다', translation: 'To dislike' },
    { id: 'mv_lh_5', moduleId: 'mastery', target: '싫어요', translation: 'I dislike it' },
    { id: 'mv_lh_6', moduleId: 'mastery', target: '싫음', translation: 'Dislike' },
    { id: 'mv_lh_7', moduleId: 'mastery', target: '옳다', translation: 'To be right / correct' },
    { id: 'mv_lh_8', moduleId: 'mastery', target: '옳은', translation: 'Right / Just' },
    { id: 'mv_lh_9', moduleId: 'mastery', target: '옳고 그름', translation: 'Right and wrong' },
    { id: 'mv_lh_10', moduleId: 'mastery', target: '끓다', translation: 'To boil' },
    { id: 'mv_lh_11', moduleId: 'mastery', target: '끓이다', translation: 'To brew / boil' },
    { id: 'mv_lh_12', moduleId: 'mastery', target: '닳다', translation: 'To wear out' },
  ],
  'ㄳ': [
    { id: 'mv_gs_1', moduleId: 'mastery', target: '몫', translation: 'Share / Portion' },
    { id: 'mv_gs_2', moduleId: 'mastery', target: '제 몫', translation: 'One’s own share' },
    { id: 'mv_gs_3', moduleId: 'mastery', target: '몫을 하다', translation: 'Do one’s part' },
    { id: 'mv_gs_4', moduleId: 'mastery', target: '삯', translation: 'Wages / Fare' },
    { id: 'mv_gs_5', moduleId: 'mastery', target: '품삯', translation: 'Day-labor wage' },
    { id: 'mv_gs_6', moduleId: 'mastery', target: '길삯', translation: 'Travel fare' },
    { id: 'mv_gs_7', moduleId: 'mastery', target: '뱃삯', translation: 'Boat fare' },
    { id: 'mv_gs_8', moduleId: 'mastery', target: '차삯', translation: 'Vehicle fare' },
    { id: 'mv_gs_9', moduleId: 'mastery', target: '일삯', translation: 'Daily wage' },
    { id: 'mv_gs_10', moduleId: 'mastery', target: '넋', translation: 'Soul / Spirit' },
    { id: 'mv_gs_11', moduleId: 'mastery', target: '넋두리', translation: 'Lamentation / Grumbling' },
    { id: 'mv_gs_12', moduleId: 'mastery', target: '넋을 잃다', translation: 'To be stunned / entranced' },
  ],
  'ㄾ': [
    { id: 'mv_lt_1', moduleId: 'mastery', target: '핥다', translation: 'To lick' },
    { id: 'mv_lt_2', moduleId: 'mastery', target: '핥아요', translation: 'Lick / Licks' },
    { id: 'mv_lt_3', moduleId: 'mastery', target: '핥아 먹다', translation: 'To lap up' },
    { id: 'mv_lt_4', moduleId: 'mastery', target: '핥음', translation: 'Licking' },
    { id: 'mv_lt_5', moduleId: 'mastery', target: '핥기', translation: 'Licking action' },
    { id: 'mv_lt_6', moduleId: 'mastery', target: '훑다', translation: 'To browse / skim' },
    { id: 'mv_lt_7', moduleId: 'mastery', target: '훑어요', translation: 'Skims / Scans' },
    { id: 'mv_lt_8', moduleId: 'mastery', target: '훑어보다', translation: 'To glance over / skim' },
    { id: 'mv_lt_9', moduleId: 'mastery', target: '훑기', translation: 'Skimming' },
    { id: 'mv_lt_10', moduleId: 'mastery', target: '훑어내다', translation: 'To strip off / weed out' },
    { id: 'mv_lt_11', moduleId: 'mastery', target: '훑어 읽다', translation: 'To skim-read' },
  ],
  'ㄿ': [
    { id: 'mv_lp_1', moduleId: 'mastery', target: '읊다', translation: 'To recite poem' },
    { id: 'mv_lp_2', moduleId: 'mastery', target: '읊어요', translation: 'Recite / Chants' },
    { id: 'mv_lp_3', moduleId: 'mastery', target: '읊조리다', translation: 'To murmur a poem' },
    { id: 'mv_lp_4', moduleId: 'mastery', target: '읊조림', translation: 'Poetic murmuring' },
    { id: 'mv_lp_5', moduleId: 'mastery', target: '시를 읊다', translation: 'To recite a poem' },
    { id: 'mv_lp_6', moduleId: 'mastery', target: '시를 읊어요', translation: 'Reciting a poem' },
    { id: 'mv_lp_7', moduleId: 'mastery', target: '노래를 읊다', translation: 'To chant a song' },
    { id: 'mv_lp_8', moduleId: 'mastery', target: '읊는 소리', translation: 'Sound of reciting' },
    { id: 'mv_lp_9', moduleId: 'mastery', target: '읊기', translation: 'Recitation' },
    { id: 'mv_lp_10', moduleId: 'mastery', target: '읊어보다', translation: 'Try reciting' },
    { id: 'mv_lp_11', moduleId: 'mastery', target: '되읊다', translation: 'To recite again' },
  ],
  'ㄽ': [
    { id: 'mv_ls_1', moduleId: 'mastery', target: '외곬', translation: 'Single-minded path' },
    { id: 'mv_ls_2', moduleId: 'mastery', target: '외곬수', translation: 'Single-minded person' },
    { id: 'mv_ls_3', moduleId: 'mastery', target: '외곬으로', translation: 'Steadfastly / In a single direction' },
    { id: 'mv_ls_4', moduleId: 'mastery', target: '외곬 인생', translation: 'Single-minded devotion in life' },
    { id: 'mv_ls_5', moduleId: 'mastery', target: '외곬 길', translation: 'Single one-way path' },
    { id: 'mv_ls_6', moduleId: 'mastery', target: '외곬 마음', translation: 'Devoted unswerving heart' },
    { id: 'mv_ls_7', moduleId: 'mastery', target: '외곬 생각', translation: 'Single-minded thought' },
    { id: 'mv_ls_8', moduleId: 'mastery', target: '외곬 사랑', translation: 'Steadfast undivided love' },
    { id: 'mv_ls_9', moduleId: 'mastery', target: '외곬 열정', translation: 'Unwavering single passion' },
    { id: 'mv_ls_10', moduleId: 'mastery', target: '한 외곬', translation: 'A single focused path' },
    { id: 'mv_ls_11', moduleId: 'mastery', target: '외곬 삶', translation: 'Single-minded life' },
  ],
};

/**
 * Curated sentence banks for each Sentence Milestone Checkpoint.
 * Every sentence is verified to contain only letters unlocked up to that milestone.
 */
export const MASTERY_CHECKPOINT_SENTENCES: Record<string, LessonItem[]> = {
  // Checkpoint 1: Home Row Sentences (ㅓ, ㅏ, ㅇ, ㄹ, ㅗ, ㅣ, ㅁ, ㄴ, ㅎ, ㅜ, ㅡ)
  'cp_home_row': [
    { id: 'cp1_1', moduleId: 'mastery', target: '어머니와 아이', translation: 'Mother and child' },
    { id: 'cp1_2', moduleId: 'mastery', target: '우리 어머니와 누나', translation: 'Our mother and older sister' },
    { id: 'cp1_3', moduleId: 'mastery', target: '나무 위로 날아오르나', translation: 'Does it fly up above the tree?' },
    { id: 'cp1_4', moduleId: 'mastery', target: '하늘 위로 흐르는 물', translation: 'Water flowing skyward' },
    { id: 'cp1_5', moduleId: 'mastery', target: '이름은 하나', translation: 'The name is one' },
    { id: 'cp1_6', moduleId: 'mastery', target: '눈물이 흐르는 날', translation: 'A day when tears flow' },
    { id: 'cp1_7', moduleId: 'mastery', target: '너와 나의 마음', translation: 'Heart of you and me' },
    { id: 'cp1_8', moduleId: 'mastery', target: '하나 모아 우리 마음', translation: 'Gathering one by one, our hearts' },
    { id: 'cp1_9', moduleId: 'mastery', target: '어머니 마음은 하늘', translation: 'Mother’s heart is the sky' },
    { id: 'cp1_10', moduleId: 'mastery', target: '눈물 어린 너의 눈', translation: 'Your tearful eyes' },
    { id: 'cp1_11', moduleId: 'mastery', target: '물 위로 흐르는 하루', translation: 'A day flowing upon the water' },
    { id: 'cp1_12', moduleId: 'mastery', target: '하루하루 늘어나는 힘', translation: 'Strength increasing day by day' },
    { id: 'cp1_13', moduleId: 'mastery', target: '머리 위로 오른 은하', translation: 'Milky Way risen above the head' },
    { id: 'cp1_14', moduleId: 'mastery', target: '우리 모아 하나로', translation: 'Bringing us together as one' },
    { id: 'cp1_15', moduleId: 'mastery', target: '너와 나 우리 나라', translation: 'You and me, our nation' },
    { id: 'cp1_16', moduleId: 'mastery', target: '이마 위로 흐르는 눈물', translation: 'Tears flowing down the forehead' },
    { id: 'cp1_17', moduleId: 'mastery', target: '얼마나 멀리 오나', translation: 'How far is it coming?' },
    { id: 'cp1_18', moduleId: 'mastery', target: '마음으로 알리는 말', translation: 'Words communicated from the heart' },
    { id: 'cp1_19', moduleId: 'mastery', target: '어린 아이의 울음', translation: 'The crying of a little child' },
    { id: 'cp1_20', moduleId: 'mastery', target: '오늘 하루 힘을 모아', translation: 'Gathering strength for today' },
  ],

  // Checkpoint 2: Top + Home Row Sentences (+ ㄱ, ㅅ, ㄷ, ㅈ, ㅂ, ㅛ, ㅕ, ㅑ, ㅐ, ㅔ)
  'cp_top_row': [
    { id: 'cp2_1', moduleId: 'mastery', target: '가을 바람이 시원해요', translation: 'Autumn breeze is refreshing' },
    { id: 'cp2_2', moduleId: 'mastery', target: '바다로 여행을 가요', translation: 'Let’s go on a trip to the sea' },
    { id: 'cp2_3', moduleId: 'mastery', target: '오늘 저녁에 밥을 먹어요', translation: 'Eat dinner tonight' },
    { id: 'cp2_4', moduleId: 'mastery', target: '이웃과 재미난 이야기를 해요', translation: 'Chat fun stories with a neighbor' },
    { id: 'cp2_5', moduleId: 'mastery', target: '일어나서 운동을 해요', translation: 'Wake up and exercise' },
    { id: 'cp2_6', moduleId: 'mastery', target: '새로운 노래를 들어요', translation: 'Listen to a new song' },
    { id: 'cp2_7', moduleId: 'mastery', target: '가게에서 맛난 음식을 사요', translation: 'Buy delicious food at the store' },
    { id: 'cp2_8', moduleId: 'mastery', target: '도서관에서 조용히 공부해요', translation: 'Study quietly in the library' },
    { id: 'cp2_9', moduleId: 'mastery', target: '사랑하는 가족과 모여 살아요', translation: 'Live together with beloved family' },
    { id: 'cp2_10', moduleId: 'mastery', target: '주말에 시원한 바람을 맞아요', translation: 'Feel the cool breeze on the weekend' },
    { id: 'cp2_11', moduleId: 'mastery', target: '밤하늘에 아름다운 별을 봐요', translation: 'Look at beautiful stars in the night sky' },
    { id: 'cp2_12', moduleId: 'mastery', target: '매일 조금 더 발전하는 나', translation: 'Me improving a little more every day' },
    { id: 'cp2_13', moduleId: 'mastery', target: '세상 곳곳을 여행하며 살아요', translation: 'Travel all over the world and live' },
    { id: 'cp2_14', moduleId: 'mastery', target: '여름 바닷가에서 수영을 해요', translation: 'Swim at the summer beach' },
    { id: 'cp2_15', moduleId: 'mastery', target: '방 안을 조용하게 정리해요', translation: 'Quietly tidy up the room' },
    { id: 'cp2_16', moduleId: 'mastery', target: '지갑과 물건을 잘 모아요', translation: 'Collect wallet and items well' },
    { id: 'cp2_17', moduleId: 'mastery', target: '가을 바람에 노래를 불러요', translation: 'Sing a song in the autumn wind' },
  ],

  // Checkpoint 3: Full Alphabet Sentences (+ ㅋ, ㅌ, ㅊ, ㅍ, ㅠ)
  'cp_bottom_row': [
    { id: 'cp3_1', moduleId: 'mastery', target: '시원한 커피 한 잔의 여유', translation: 'Relaxing with a cup of cool coffee' },
    { id: 'cp3_2', moduleId: 'mastery', target: '기차를 타고 여행을 가요', translation: 'Take a train and go on a trip' },
    { id: 'cp3_3', moduleId: 'mastery', target: '친구에게 보낼 편지를 적어요', translation: 'Write a letter to send to a friend' },
    { id: 'cp3_4', moduleId: 'mastery', target: '달콤한 포도와 토마토를 먹어요', translation: 'Eat sweet grapes and tomatoes' },
    { id: 'cp3_5', moduleId: 'mastery', target: '창문을 열고 시원한 공기를 마셔요', translation: 'Open the window and breathe cool air' },
    { id: 'cp3_6', moduleId: 'mastery', target: '피아노 소리가 아름답게 울려요', translation: 'The piano sound echoes beautifully' },
    { id: 'cp3_7', moduleId: 'mastery', target: '휴일에 집에서 푹 쉬어요', translation: 'Rest comfortably at home on the holiday' },
    { id: 'cp3_8', moduleId: 'mastery', target: '택시를 타고 공항으로 가요', translation: 'Take a taxi to the airport' },
    { id: 'cp3_9', moduleId: 'mastery', target: '책을 보며 깊은 생각에 잠겨요', translation: 'Look at a book and get lost in deep thought' },
    { id: 'cp3_10', moduleId: 'mastery', target: '카메라로 추억을 사진에 담아요', translation: 'Capture memories in photos with a camera' },
    { id: 'cp3_11', moduleId: 'mastery', target: '파도가 밀려오는 해변을 걸어요', translation: 'Walk along the beach where waves roll in' },
    { id: 'cp3_12', moduleId: 'mastery', target: '우체국에서 편지에 우표를 붙여요', translation: 'Stick a postage stamp on the letter at the post office' },
    { id: 'cp3_13', moduleId: 'mastery', target: '치마를 입고 외출을 준비해요', translation: 'Put on a skirt and prepare to go out' },
    { id: 'cp3_14', moduleId: 'mastery', target: '탁자 위에 커피잔을 놓아요', translation: 'Place the coffee cup on top of the table' },
    { id: 'cp3_15', moduleId: 'mastery', target: '신나는 음악에 맞춰 춤을 춰요', translation: 'Dance in rhythm to exciting music' },
  ],

  // Checkpoint 4: Shift Key Sentences (+ ㄲ, ㅆ, ㄸ, ㅉ, ㅃ, ㅒ, ㅖ)
  'cp_shift_keys': [
    { id: 'cp4_1', moduleId: 'mastery', target: '꽃집에서 예쁜 꽃을 골라요', translation: 'Pick pretty flowers at the florist' },
    { id: 'cp4_2', moduleId: 'mastery', target: '뚝배기에 보글보글 맛있는 찌개', translation: 'Delicious stew boiling bubble-bubble in an earthen pot' },
    { id: 'cp4_3', moduleId: 'mastery', target: '갓 구운 따끈따끈한 빵 냄새', translation: 'Smell of freshly baked warm bread' },
    { id: 'cp4_4', moduleId: 'mastery', target: '딸기잼을 바른 토스트를 먹어요', translation: 'Eat toast spread with strawberry jam' },
    { id: 'cp4_5', moduleId: 'mastery', target: '진짜 재미있는 옛날이야기', translation: 'A truly fascinating old folktale' },
    { id: 'cp4_6', moduleId: 'mastery', target: '시계를 보며 약속 시간을 지켜요', translation: 'Check the clock and keep the appointment on time' },
    { id: 'cp4_7', moduleId: 'mastery', target: '꿈을 향해 한 걸음씩 나아가요', translation: 'Step forward toward your dreams' },
    { id: 'cp4_8', moduleId: 'mastery', target: '어릴 적 추억이 깃든 골목길', translation: 'An alleyway filled with childhood memories' },
    { id: 'cp4_9', moduleId: 'mastery', target: '날씨 예보를 미리 확인해요', translation: 'Check the weather forecast in advance' },
    { id: 'cp4_10', moduleId: 'mastery', target: '친구와 함께 나누는 즐거운 얘기', translation: 'Pleasant conversation shared with a friend' },
    { id: 'cp4_11', moduleId: 'mastery', target: '빨래를 널고 햇살을 만끽해요', translation: 'Hang the laundry and enjoy the sunshine' },
    { id: 'cp4_12', moduleId: 'mastery', target: '꼬마 아이가 활짝 웃고 있어요', translation: 'The little child is smiling brightly' },
    { id: 'cp4_13', moduleId: 'mastery', target: '식사 예절을 바르게 지켜요', translation: 'Observe dining etiquette properly' },
    { id: 'cp4_14', moduleId: 'mastery', target: '쌀을 씻어서 맛있는 밥을 지어요', translation: 'Wash the rice and cook delicious meals' },
    { id: 'cp4_15', moduleId: 'mastery', target: '짜장면과 탕수육을 주문해요', translation: 'Order black bean noodles and sweet and sour pork' },
  ],

  // Checkpoint 5: Master Review & Complex Passages (+ Compound Batchim)
  'cp_master': [
    { id: 'cp5_1', moduleId: 'mastery', target: '많은 책을 읽으며 지식을 넓혀요', translation: 'Expand knowledge by reading many books' },
    { id: 'cp5_2', moduleId: 'mastery', target: '의자에 편안하게 앉아서 쉬어요', translation: 'Sit comfortably in the chair and rest' },
    { id: 'cp5_3', moduleId: 'mastery', target: '닭고기로 끓인 따뜻한 삼계탕', translation: 'Warm chicken soup cooked with ginseng' },
    { id: 'cp5_4', moduleId: 'mastery', target: '맑은 가을 하늘 아래 넓은 들판', translation: 'Wide open field under a clear autumn sky' },
    { id: 'cp5_5', moduleId: 'mastery', target: '젊은 날의 소중한 꿈과 삶', translation: 'Precious dreams and life of youth' },
    { id: 'cp5_6', moduleId: 'mastery', target: '어려움이 있어도 희망을 잃지 않아요', translation: 'Never lose hope even through hardship' },
    { id: 'cp5_7', moduleId: 'mastery', target: '값진 경험이 인생의 큰 자산이 됩니다', translation: 'Valuable experiences become great assets in life' },
    { id: 'cp5_8', moduleId: 'mastery', target: '비 온 뒤에 땅이 굳어진다는 속담', translation: 'Proverb that ground hardens after rain' },
    { id: 'cp5_9', moduleId: 'mastery', target: '자신의 몫을 다하는 성실한 태도', translation: 'A sincere attitude fulfilling one’s own share' },
    { id: 'cp5_10', moduleId: 'mastery', target: '외곬으로 한 우물을 파는 장인정신', translation: 'Craftsmanship devoting oneself to a single pursuit' },
    { id: 'cp5_11', moduleId: 'mastery', target: '밤하늘의 별을 보며 시를 읊어요', translation: 'Recite poetry looking up at the night stars' },
    { id: 'cp5_12', moduleId: 'mastery', target: '흙 냄새 가득한 고향의 시골길', translation: 'Country road filled with the scent of soil' },
    { id: 'cp5_13', moduleId: 'mastery', target: '서로를 닮아가는 정다운 사람들의 모습', translation: 'Loving people growing to resemble one another' },
    { id: 'cp5_14', moduleId: 'mastery', target: '마음이 넓고 너그러운 태도를 가져요', translation: 'Have an open-minded and generous attitude' },
    { id: 'cp5_15', moduleId: 'mastery', target: '많은 경험을 쌓아서 값진 지혜를 얻어요', translation: 'Gain valuable wisdom by accumulating many experiences' },
    { id: 'cp5_16', moduleId: 'mastery', target: '맑은 강물에서 물고기가 헤엄쳐요', translation: 'Fish swim in the clear river water' },
    { id: 'cp5_17', moduleId: 'mastery', target: '어려운 이웃을 보면 결코 굶기지 않아요', translation: 'Never let neighbors go hungry when in difficulty' },
    { id: 'cp5_18', moduleId: 'mastery', target: '젊은 시절의 소중한 추억을 잊지 않아요', translation: 'Never forget precious memories of youth' },
    { id: 'cp5_19', moduleId: 'mastery', target: '넓은 바다를 바라보며 새로운 꿈을 꿔요', translation: 'Dream new dreams looking out at the wide ocean' },
    { id: 'cp5_20', moduleId: 'mastery', target: '책을 훑어보고 중요한 내용을 정리해요', translation: 'Skim the book and organize important content' },
    { id: 'cp5_21', moduleId: 'mastery', target: '시를 읊으며 감미로운 선율을 느껴요', translation: 'Feel the sweet melody while reciting a poem' },
    { id: 'cp5_22', moduleId: 'mastery', target: '옳은 선택을 하기 위해 깊이 생각해요', translation: 'Think deeply to make the right choice' },
    { id: 'cp5_23', moduleId: 'mastery', target: '가족과 함께 식탁에 앉아서 닭요리를 먹어요', translation: 'Sit at the table with family and eat chicken dish' },
    { id: 'cp5_24', moduleId: 'mastery', target: '자신의 삶을 사랑하고 하루를 값지게 살아요', translation: 'Love one’s own life and live each day valuably' },
    { id: 'cp5_25', moduleId: 'mastery', target: '축하합니다! 모든 한글 자모를 마스터하셨습니다.', translation: 'Congratulations! You have mastered all Korean Hangul Jamos.' },
  ],
};
